### ISSUE TITLE
Microsoft.KeyVault/vaults/secrets (2018-02-14)

### ISSUE THREAD

**Issue by neilpeterson** [Azure/arm-template-whatif#10]
## Describe the noise

**Resource type**

Microsoft.KeyVault/vaults/secrets

**apiVersion**

2018-02-14

**Client**

PowerShell

**Relevant ARM Template code**

```
{
	"type": "secrets",
	"name": "nepeters",
	"apiVersion": "2018-02-14",
	"dependsOn": [
		"[resourceId('Microsoft.KeyVault/vaults', 'nepeters')]"
	],
	"properties": {
		"value": "nepeters"
	}
}
```

**Expected response**

I expected no noise since the template has not been modified since the resources were deployed.

**Current (noisy) response**

```
Resource and property changes are indicated with these symbols:
  - Delete
  + Create
  ~ Modify
  = NoChange

The deployment will update the following scope:

Scope: /subscriptions/3762d87c-ddb8-425f-b2fc-29e5e859edaf/resourceGroups/whatif-kv3

  ~ Microsoft.KeyVault/vaults/nepeters/secrets/nepeters [2018-02-14]
    - location:         "eastus"
    - properties.attributes:

        created: 1575248425
        enabled: true
        updated: 1575248425

    + properties.value: "nepeters"

  = Microsoft.KeyVault/vaults/nepeters [2018-02-14]

Resource changes: 1 to modify, 1 no change.
```

**Additional context**

Parent resource `Microsoft.KeyVault/vaults` validates without issue or noise.

**Comment by majastrz** [comment]
The fix for masking `value` and removing the read only properties `created` and `updated` has been committed to an internal repo and is awaiting deployment. We are still working for the fix for the default property `enabled`.

**Comment by majastrz** [comment]
The fix for the read only properties has been deployed to all public regions. The fix for the enabled property has been committed to an internal repo and is awaiting deployment (should be live in all public regions by end of next week).

**Comment by majastrz** [comment]
@neilpeterson, all the fixes should now be deployed to all public regions. Can you confirm it's working as expected for you?

**Comment by shenglol** [comment]
We are closing the issue. Feel free to reopen it if you still see the noise.
