### ISSUE TITLE
Microsoft.Network/applicationGateways existing IDs marked as Delete

### ISSUE THREAD

**Issue by fulder** [Azure/arm-template-whatif#100]
## Describe the noise

IDs for some of application gateway resources are marked for Deletion although they are specified in the ARM templates. The error seems to be missing IDs in nested resources which doesn't exist (e.g. `backendAddressPools.properties.pathRules`).

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.Network/applicationGateways

**apiVersion** (i.e. 2019-04-01)
2019-11-01

**Client (PowerShell, Azure CLI, or API)**
Azure CLI 2.8.0

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**
```
...
"backendAddressPools": [
   {
     "id": "[concat(resourceId('Microsoft.Network/applicationGateways', 'myGateway'), '/backendAddressPools/', 'myBackend')]",
     "name": "myBackend",
     "properties": {
       ...
      }    
  }
]
...
"urlPathMaps":[
  {
    "id":"[concat(resourceId('Microsoft.Network/applicationGateways', 'myGateway'), '/urlPathMaps/', 'myPathMap')]",
    "name":"myPathMap",
    "properties":{
       ....
      "pathRules":[
        {
          "id":"[concat(resourceId('Microsoft.Network/applicationGateways', ',myGateway'), '/urlPathMaps/', 'myPathMap/', 'pathRules/', 'myPathRule']",
          "name":"myPathRule",
          "properties":{
             .....
            "paths":[
              "/myPath"
            ],
            "backendAddressPool":{
              "id":"[concat(resourceId('Microsoft.Network/applicationGateways', 'myGateway'), '/backendAddressPools/', 'myBackend')]"
            }
          }
        }
      ]
    }
  }
]
```

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
No noise when it comes to urlPathMaps IDs

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**
```
~ Microsoft.Network/applicationGateways/myGateway [2019-11-01]
     ~ properties.backendAddressPools: [
       ~ 0:
         - properties.pathRules: [
             0:
               id: "/subscriptions/<SUB_ID>/resourceGroups/<RG_NAME>/providers/Microsoft.Network/applicationGateways/myGateway/urlPathMaps/myPathMap/pathRules/myPathRule"
           ]

    ~ properties.backendHttpSettingsCollection: [
         ~ 0:
           - properties.pathRules: [
               0:
                 id: "/subscriptions/<SUB_ID>/resourceGroups/<RG_NAME>/providers/Microsoft.Network/applicationGateways/myGateway/urlPathMaps/myPathMap/pathRules/myPathRule"
             ]
```

**Comment by shenglol** [comment]
[w33]?

**Comment by alex-frankel** [comment]
This fix should be deployed

**Comment by fulder** [comment]
I'm still seeing this issue in North Europe and US East locations today. :crying_cat_face:

**Comment by shenglol** [comment]
@fulder Sorry for the delay, but we fixed the noise again and hopefully it will get deployed soon (which we don't control). The reason why our previous fixes didn't work is that those properties are not declared in Swagger at all, so we can to make some additional changes to integrate them into our noise suppression metadata.

[w41]?

**Comment by alex-frankel** [comment]
The fix should be fully deployed. Let us know if you are still seeing the issue.

**Comment by fulder** [comment]
Have just verified I am no longer seeing this issue. Thank you for this fix :+1:
