### ISSUE TITLE
Microsoft.OperationalInsights/workspaces noisy properties Deletion

### ISSUE THREAD

**Issue by fulder** [Azure/arm-template-whatif#101]
## Describe the noise
Re-deploying the same workspaces resource always marks some of the properties for deletion

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.OperationalInsights/workspaces

**apiVersion** (i.e. 2019-04-01)
2020-03-01-preview

**Client (PowerShell, Azure CLI, or API)**
Azure CLI 2.8.0

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**
```
{
  "name": "myWorkspace",
  "type": "Microsoft.OperationalInsights/workspaces",
  "apiVersion": "2020-03-01-preview",
  "tags": {},
  "location": "northeurope",
  "properties": {
    "sku": {
      "name": "pergb2018"
    },
    "retentionInDays": "60"
  }
}
```

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
No noise as the template has not been modified

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**
```
~ Microsoft.OperationalInsights/workspaces/myWorkspace [2020-03-01-preview]
     - properties.createdDate:  "Wed, 01 Jul 2020 09:51:43 GMT"
     - properties.features:
         enableLogAccessUsingOnlyResourcePermissions: true
         legacy:                                      0
         searchVersion:                               1
     - properties.modifiedDate: "Wed, 08 Jul 2020 10:41:18 GMT"
     - properties.source:       "Azure"
     - properties.workspaceCapping:
         dailyQuotaGb: -1.0
```

**Comment by alex-frankel** [comment]
[w32?]

**Comment by alex-frankel** [comment]
This fix should be fully deployed.

**Comment by fulder** [comment]
@alex-frankel Just a small follow-up question regarding the fix/deployment. Are there any release/change logs when it comes to what-if fixes. 

I've only seen the azure cli release notes here: https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md#tab/azure-cli but no new releases have been done there either. 

(Using the newest azure cli I am still seeing this noise right now)

**Comment by alex-frankel** [comment]
Latest noise reduction information is in #38 

The what-if noise reduction is a service-side improvement, so it's not affected by what version of the CLI you are using (unless there is a CLI specific bug)

@fulder - are you seeing the exact same noise as before? It looks like this fix has not yet rolled out to the following regions:

UK South, Australia Southeast, Germany West Central, Canada East

So if you are hitting those regions, it's possible you will not see the fix. Otherwise @Xynoclafe can take a look.

**Comment by fulder** [comment]
@alex-frankel Thanks for the info!

I was running `what-if` with a template in North Europe region and still saw the exact same noise today.

**Comment by Xynoclafe** [comment]
I'll take another look at it.

**Comment by shenglol** [comment]
@fulder @alex-frankel @Xynoclafe Sorry I think I made a mistake on the week number. The fix is actually in build w33 but not w32. It got deployed to Canary, but we'll have to wait for a few more days for it to hit other regions.

**Comment by alex-frankel** [comment]
This fix should be deployed

**Comment by fulder** [comment]
I'm still seeing this issue in North Europe location today. :crying_cat_face:

**Comment by shenglol** [comment]
@fulder thanks for reporting it. We found that some of the read-only properties are not declared in Swagger at all, so we need to make some additional changes on our side. The following noise should be fixed though:

```
- properties.workspaceCapping:
         dailyQuotaGb: -1.0
```
Is it still showing in your result?

**Comment by fulder** [comment]
> ```
> - properties.workspaceCapping:
>          dailyQuotaGb: -1.0
> ```
> 
> Is it still showing in your result?

This is not showing in my results anymore :) but the rest of the properties are still there.

**Comment by shenglol** [comment]
> > ```
> > - properties.workspaceCapping:
> >          dailyQuotaGb: -1.0
> > ```
> > 
> > 
> > Is it still showing in your result?
> 
> This is not showing in my results anymore :) but the rest of the properties are still there.

I see. We just committed changes to fix the other properties. It will take another couple of weeks for them to be deployed. Sorry that we had to open this again :(

**Comment by fulder** [comment]
No problem :) One step closer to cleaning up this noise. Waiting for the deployment :+1:

**Comment by alex-frankel** [comment]
[w40]

**Comment by alex-frankel** [comment]
This fix should be deployed. Let us know if you are still seeing this issue.

**Comment by fulder** [comment]
Have verified I don't see this noise anymore. Works just fine. Thank you for this fix! :+1:
