### ISSUE TITLE
NOISE REPORT: Microsoft.Automation/automationAccounts properties

### ISSUE THREAD

**Issue by mariolopjr** [Azure/arm-template-whatif#104]
## Describe the noise
Properties not included being marked for deletion. Adds noise (I assume the property in quest is _not_ being deleted when deploying).

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.Automation/automationAccounts

**apiVersion** (i.e. 2019-04-01)
2015-10-31

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**
```json
  {
      "name": "[variables('environmentSpecificConfig')[parameters('environment')].automationAccountName]",
      "type": "Microsoft.Automation/automationAccounts",
      "location": "[resourceGroup().location]",
      "apiVersion": "2015-10-31",
      "tags": "[variables('resourceTags')]",
      "properties": {
        "sku": {
          "name": "Basic"
        }
      }
    }
```

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
I expected no noise since the template has not been modified since the resources were deployed

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**
```
  ~ Microsoft.Automation/automationAccounts/ACCOUNT_NAME [2015-10-31]
    - properties.RegistrationUrl: "https://12345678-1234-1234-1234-123456789012.agentsvc.eus.azure-automation.net/accounts/12345678-1234-1234-1234-123456789012"
```

**Additional context**
N/A

**Comment by shenglol** [comment]
[w31]

**Comment by alex-frankel** [comment]
Fix should be fully deployed
