### ISSUE TITLE
Switch Parameter on the -Whatif doesn’t seem to behave correctly

### ISSUE THREAD

**Issue by brwilkinson** [Azure/arm-template-whatif#106]
Switch Parameter on the -Whatif doesn’t seem to behave correctly?

If you set a switch to -switch:$False then that value should not execute, however in the case of -whatif, it shows the status “Getting the latest status of all resources…”.

It’s only the message that still shows, and it takes some extra time, however then it doesn’t actually give the whatif output.

![image](https://user-images.githubusercontent.com/3605266/88432625-6c69cd00-cdb1-11ea-9f1d-914e64c0ad40.png)

**Comment by shenglol** [comment]
Will fix it in our next release.

**Comment by alex-frankel** [comment]
Should be released by 8/25
