### ISSUE TITLE
WhatIf only works on Subsccription and ResourceGroup Level Deployments

### ISSUE THREAD

**Issue by liamfoneill** [Azure/arm-template-whatif#107]
**Describe the bug**
WhatIf only works on Subsccription and ResourceGroup Level Deployments

**To Reproduce**
Run a template deployment with -whatif switch on either a management group or tenant scoped deployment

**Expected behavior**
WhatIf would document all changes

**Screenshots**

**Client**

Any

**Additional context**
I know this is outlined in the docs here: https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-deploy-what-if?tabs=azure-powershell however it would be good to get some clarity iff this functionality is part of the design roadmap as this is something Terraform supports such as deployment of a management group and is table to run terraform plan successfully. 

https://www.terraform.io/docs/providers/azurerm/r/management_group.html

**Comment by shenglol** [comment]
Hi @liamfoneill, the What-If backend already supports tenant and MG level deployments now: 
- https://docs.microsoft.com/en-us/rest/api/resources/deployments/whatifattenantscope
- https://docs.microsoft.com/en-us/rest/api/resources/deployments/whatifatmanagementgroupscope

We've updated the Azure CLI and PowerShell modules, and they'll be available soon, see PRs:
- https://github.com/Azure/azure-cli/pull/14568
- https://github.com/Azure/azure-powershell/pull/12548

**Comment by liamfoneill** [comment]
Great thanks for letting me know. Will mark this as closed.
