### ISSUE TITLE
Microsoft.DocumentDB/databaseAccounts (2019-08-01)

### ISSUE THREAD

**Issue by neilpeterson** [Azure/arm-template-whatif#11]
## Describe the noise

**Resource type**

Microsoft.DocumentDB/databaseAccounts

**apiVersion**

2019-08-01

**Client**

PowerShell

**Relevant ARM Template code**

```
{
	"name": "nepeters",
	"type": "Microsoft.DocumentDB/databaseAccounts",
	"apiVersion": "2019-08-01",
	"location": "[resourceGroup().location]",
	"tags": {},
	"kind": "GlobalDocumentDB",
	"properties": {
		"consistencyPolicy": {
			"defaultConsistencyLevel": "Eventual",
			"maxStalenessPrefix": 1,
			"maxIntervalInSeconds": 5
		},
		"locations": [{
			"locationName": "eastus",
			"failoverPriority": 0
		}],
		"databaseAccountOfferType": "Standard",
		"enableAutomaticFailover": true,
		"capabilities": [{
			"name": "EnableTable"
		}]
	}
}
```

**Expected response**

I expected no noise since the template has not been modified since the resources were deployed.

**Current (noisy) response**

```
Resource and property changes are indicated with these symbols:
  - Delete
  ~ Modify

The deployment will update the following scope:

Scope: /subscriptions/3762d87c-ddb8-425f-b2fc-29e5e859edaf/resourceGroups/whatif-cd

  ~ Microsoft.DocumentDB/databaseAccounts/nepeters [2019-08-01]
    - properties.disableKeyBasedMetadataWriteAccess:   false
    - properties.EnabledApiTypes:                      "Table, Sql"
    - properties.enableMultipleWriteLocations:         false
    - properties.enablePartitionKeyMonitor:            false
    - properties.isVirtualNetworkFilterEnabled:        false
    - properties.tableEndpoint:                        "https://nepeters.table.cosmos.azure.com:443/"
    ~ properties.consistencyPolicy.maxStalenessPrefix: 100 => 1
    ~ properties.locations: [
      ~ 0:

        - isZoneRedundant: false

      ]

Resource changes: 1 to modify.
```

**Comment by alex-frankel** [comment]
@neilpeterson, can you double check one property in particular?

   ~ properties.consistencyPolicy.maxStalenessPrefix: 100 => 1

This looks like the resource was originally created with a maxStalenessPrefix of 100, and in the second deployment it got changed to 1. Could that be right?

**Comment by neilpeterson** [comment]
Hm, it looks like something is changing the property during creation. I've deployed a new instance using a template built from the VS Code extension snippet;  `maxStalenessPrefix` is `1`. 

```
"consistencyPolicy": {
    "defaultConsistencyLevel": "Eventual",
    "maxStalenessPrefix": 1,
    "maxIntervalInSeconds": 5
}
```

When running a query on the property after deployment, I do see that it has changed to 100.

```
$ az cosmosdb show -n nepeters02 -g whatif-cd --query consistencyPolicy.maxStalenessPrefix
                                 
100
```

Quick look at [docs](https://docs.microsoft.com/en-us/azure/templates/microsoft.documentdb/2019-08-01/databaseaccounts#consistencypolicy-object), and it seems `1` should be a valid value.

In any regard, it does appear that this is not a what-if issue.

**Comment by majastrz** [comment]
@neilpeterson, thanks for confirming that 100 => 1 was a legitimate change.

**Comment by majastrz** [comment]
The fixes have now been committed to an internal repo and are awaiting deployment. [w18]
