### ISSUE TITLE
Microsoft.DocumentDB/databaseAccounts@2020-04-01

### ISSUE THREAD

**Issue by alex-frankel** [Azure/arm-template-whatif#114]
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.DocumentDB/databaseAccounts

**apiVersion** (i.e. 2019-04-01)
2020-04-01

**Client (PowerShell, Azure CLI, or API)**
CLI

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**
```
    {
      "type": "Microsoft.DocumentDB/databaseAccounts",
      "apiVersion": "2020-04-01",
      "name": "[variables('cosmosAccountName')]",
      "location": "[parameters('location')]",
      "kind": "GlobalDocumentDB",
      "properties": {
        "consistencyPolicy": {
          "defaultConsistencyLevel": "Session"
        },
        "locations": [
          {
            "locationName": "[parameters('location')]",
            "failoverPriority": 0,
            "isZoneRedundant": false
          }
        ],
        "databaseAccountOfferType": "Standard"
      }
    },
```

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
No noise

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**
![image](https://user-images.githubusercontent.com/11078275/90791508-20ca1680-e2be-11ea-8247-3cad8f3084e5.png)

**Additional context**

**Comment by shenglol** [comment]
[w42].

**Comment by alex-frankel** [comment]
The fix should be fully deployed. Let us know if you are still seeing the issue.
