### ISSUE TITLE
Microsoft.Network/connections

### ISSUE THREAD

**Issue by slavizh** [Azure/arm-template-whatif#117]
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.Network/connections

**apiVersion** (i.e. 2019-04-01)
2020-05-01

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
No change.
**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

```
  ~ Microsoft.Network/connections/test-t-wan-vpn-gw2-to-lgw-1 [2020-05-01]
    - properties.packetCaptureDiagnosticState: "None"

```

**Comment by detienne20** [comment]
w40

**Comment by alex-frankel** [comment]
This fix should be deployed. Let us know if you are still seeing this issue.
