### ISSUE TITLE
Microsoft.Network/virtualNetworkGateways

### ISSUE THREAD

**Issue by slavizh** [Azure/arm-template-whatif#118]
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.Network/virtualNetworkGateways

**apiVersion** (i.e. 2019-04-01)
2019-09-01

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
No change

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

```
 ~ Microsoft.Network/virtualNetworkGateways/test-t-wan-vpn-gw2 [2019-09-01]
    - properties.bgpSettings.bgpPeeringAddress: "<Ip address>"
    - properties.bgpSettings.bgpPeeringAddresses: [
        0:

          defaultBgpIpAddresses: [
            0: "<ip address>"
          ]
          ipconfigurationId: "<resource id of ip configuration>"
          tunnelIpAddresses: [
            0: "<Ip Address>"
          ]

      ]
    - properties.enablePrivateIpAddress:        false
    - properties.packetCaptureDiagnosticState:  "None"
[
      ~ 0:

        - id:   "<ip configuration resource id>"
        - type: "Microsoft.Network/virtualNetworkGateways/ipConfigurations"

      ]

```

**Additional context**

**Comment by shenglol** [comment]
[w46].

**Comment by alex-frankel** [comment]
This fix should be fully deployed. Let us know if you are still setting this issue.
