### ISSUE TITLE
Microsoft.Sql/servers (2015-05-01-preview)

### ISSUE THREAD

**Issue by neilpeterson** [Azure/arm-template-whatif#12]
## Describe the noise

**Resource type**

Microsoft.Sql/servers

**apiVersion**

2015-05-01-preview

**Client**

PowerShell

**Relevant ARM Template code**

```
{
	"name": "nepeters",
	"type": "Microsoft.Sql/servers",
	"apiVersion": "2015-05-01-preview",
	"location": "[resourceGroup().location]",
	"properties": {
		"administratorLogin": "neillocal",
		"administratorLoginPassword": "Password2020!"
	}
}
```

**Expected response**

I expected no noise since the template has not been modified since the resources were deployed.

**Current (noisy) response**

```
Resource and property changes are indicated with these symbols:
  - Delete
  ~ Modify
  * Ignore

The deployment will update the following scope:

Scope: /subscriptions/3762d87c-ddb8-425f-b2fc-29e5e859edaf/resourceGroups/whatif-sql

  ~ Microsoft.Sql/servers/nepeters [2015-05-01-preview]
    - kind:               "v12.0"
    - properties.version: "12.0"

  * Microsoft.Sql/servers/nepeters/databases/master

Resource changes: 1 to modify, 1 to ignore.
```

**Comment by shenglol** [comment]
This can be closed together with https://github.com/Azure/arm-template-whatif/issues/21 once [w17] deployment is complete.

**Comment by alex-frankel** [comment]
The fix should be deployed. Please reopen the issue if you still see this noise.
