### ISSUE TITLE
Microsoft.DBforPostgreSQL/servers/databases

### ISSUE THREAD

**Issue by slavizh** [Azure/arm-template-whatif#120]
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.DBforPostgreSQL/servers/databases

**apiVersion** (i.e. 2019-04-01)
2017-12-01

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
no change

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

```
~ Microsoft.DBforPostgreSQL/servers/lz-postgresql01/databases/test_db [2017-12-01]
    ~ properties.charset: "UTF8" => "utf8"

```

**Additional context**

**Comment by shenglol** [comment]
[w45].

**Comment by alex-frankel** [comment]
This fix should be fully deployed. Let us know if you are still setting this issue.
