### ISSUE TITLE
Security - Microsoft.DBforPostgreSQL/servers

### ISSUE THREAD

**Issue by slavizh** [Azure/arm-template-whatif#122]
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.DBforPostgreSQL/servers

**apiVersion** (i.e. 2019-04-01)
2017-12-01

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
Should not show property administratorLoginPassword in plain text.

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

Shows property administratorLoginPassword value in plain text.

**Additional context**

**Comment by shenglol** [comment]
[w40].

**Comment by alex-frankel** [comment]
This fix should be deployed. Let us know if you are still seeing this issue.
