### ISSUE TITLE
what-if plan for Application Gateway

### ISSUE THREAD

**Issue by smits23** [Azure/arm-template-whatif#125]
When you make a change in backend https setting or listener, routing rules  settings in application gateway, what-if plan displays that resources are getting deleted whereas in actual only the modified resource gets deleted and all other changes remain unaffected. 
Will this issue be addressed? 
Also the formatting on agw what-if has a lot of unnecessary noise.

**Comment by alex-frankel** [comment]
Can you share the a screengrab (or the text) from the what-if response? We need a bit more detail before we can do the fix.

**Comment by smits23** [comment]
[agw_whatif-ss.docx](https://github.com/Azure/arm-template-whatif/files/5227105/agw_whatif-ss.docx)

Steps to reproduce:
1. Create an agw with multiple https listener, backendpool, http settings, routing rule (at least 2) 
2. Remove one of the listener, https setting, routing rule 

Verify the plan using what if (i used powershell command and CLI, andbot had same results) please review the screenshot attached

**Comment by alex-frankel** [comment]
_cc @shenglol to check what I'm saying is accurate_

the doc has all of the color encoding information in the screenshot, so it is difficult for me to parse. What command are you running? In CLI if you add the `--no-pretty-print` parameter, the output will be cleaner. Can you try running with the flag and resending? Are you running this inside of a pipeline?

**Comment by smits23** [comment]
Do you have a PowerShell equivalent command for this?

Regards,
Smita Sukumaran
Software Development Engineer I | Information Technology
[GM Financial]
817-525-7618(W) |
713-806-9156(M)
smita.sukumaran@GMFinancial.com<mailto:smita.sukumaran@GMFinancial.com>
[cid:image002.png@01D623B9.2E4A6E00]

**Comment by shenglol** [comment]
@smits23 If you are running the What-If CLI command in some pipeline you can set the environment variable `AZURE_CORE_NO_COLOR=true` to strip out the ANSI color escaping sequences in the What-If output.

For the PowerShell cmdlet, we don't have a way to disable color.

**Comment by alex-frankel** [comment]
@smits23 - have you seen the latest response here? Can you try sending us the original template?

**Comment by smits23** [comment]
Hello,
My apologies for being late, I tried using  --pretty-print in CLI and that resolved the format issue. But what I don’t understand is “Changes section” inn agw displays the entire json output instead of what exactly is being updated. Sharing a snapshot from pipeline output:

[cid:image008.png@01D6929F.7D6C1920]


Steps to reproduce:

Create an AGW (here in this it a v-1 version )

1.       Create backend config with 2 https listener, backend pool, routing rules, https settings (https)

2.       Delete one of the listener, https setting routing rule

3.       Check the plan

4.       Does it display only the expected changes in AGW config?

Please note: You can see the format issue is one, but what I am concerned about is reporting the right changes in the AGW deployment plan.


Regards,
Smita Sukumaran
Software Development Engineer I | Information Technology
[GM Financial]
817-525-7618(W) |
713-806-9156(M)
smita.sukumaran@GMFinancial.com<mailto:smita.sukumaran@GMFinancial.com>

[cid:image002.png@01D623B9.2E4A6E00] [cid:image003.png@01D6923F.4EAD3F20]

**Comment by smits23** [comment]
Also I looked at the changeType:

[cid:image001.png@01D692A0.66196010]


The modify section says one of the backendHttpSettingsCollection is being deleted. But in actual this specific backendHttpSettingsCollection is not being deleted. Please can do so some testing in your local environment and let me know if you see anything different?


Unless I am not reading the results correctly.


Regards,
Smita Sukumaran
Software Development Engineer I | Information Technology
[GM Financial]
817-525-7618(W) |
713-806-9156(M)
smita.sukumaran@GMFinancial.com<mailto:smita.sukumaran@GMFinancial.com>

[cid:image002.png@01D623B9.2E4A6E00] [cid:image003.png@01D6923F.4EAD3F20]

**Comment by alex-frankel** [comment]
The image you included is not being shown in the github issue page. Can you respond directly on github.com instead of replying by email?

**Comment by smits23** [comment]
Ok sure will do.


Sent with BlackBerry Work
(www.blackberry.com)

**Comment by smits23** [comment]
Please let me know if you can see the images now?

**Comment by shenglol** [comment]
Yes we can see the images now. Thanks for sharing them. I'll look into this today.

**Comment by shenglol** [comment]
The noise are due to read-only properties. We are working on fixing them.

**Comment by smits23** [comment]
Thank you.

Regards,
Smita Sukumaran
Software Development Engineer I | Information Technology
[GM Financial]
817-525-7618(W) |
713-806-9156(M)
smita.sukumaran@GMFinancial.com<mailto:smita.sukumaran@GMFinancial.com>

[cid:image002.png@01D623B9.2E4A6E00] [cid:image003.png@01D6923F.4EAD3F20]

**Comment by alex-frankel** [comment]
The fix should be fully deployed. Let us know if you are still seeing the issue.

**Comment by smits23** [comment]
Ok will do. Thank you

**Comment by smits23** [comment]
Is it updated for both bash and powershell?

**Comment by alex-frankel** [comment]
Yep!
