### ISSUE TITLE
what-if shows two resourceGroup scopes with different casing

### ISSUE THREAD

**Issue by alex-frankel** [Azure/arm-template-whatif#126]
![image](https://user-images.githubusercontent.com/11078275/93256720-98ba1e00-f750-11ea-966d-2bf3717fd2ef.png)

**Comment by shenglol** [comment]
Close on 11/17 if the two PRs are merged before 11/11.

**Comment by alex-frankel** [comment]
This fix should be fully deployed. Let us know if you are still setting this issue.
