### ISSUE TITLE
Microsoft.Authorization/roleAssignments

### ISSUE THREAD

**Issue by slavizh** [Azure/arm-template-whatif#127]
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.Authorization/roleAssignments

**apiVersion** (i.e. 2019-04-01)
2020-04-01-preview

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**

no change. when principalType is not present in the configuration it should not show also change.

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

```
  ~ Microsoft.Network/virtualNetworks/vnet001/subnets/default/providers/Microsoft.Authorization/roleAssignments/9b630344-6a4a-5f2d-8292-3da708d1d2a8 [2020-04-01-preview]
    - properties.principalType: "ServicePrincipal"

```

**Additional context**

**Comment by detienne20** [comment]
w40

**Comment by alex-frankel** [comment]
This fix should be deployed. Let us know if you are still seeing this issue.
