### ISSUE TITLE
Microsoft.RecoveryServices/vaults/backupStorageConfig

### ISSUE THREAD

**Issue by slavizh** [Azure/arm-template-whatif#132]
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.RecoveryServices/vaults/backupStorageConfig

**apiVersion** (i.e. 2019-04-01)
2020-02-02

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
No change to the properties in what-if as they are not specified in the template. Some might be read-only. Properties that are specified in the template are storageModelType and crossRegionRestoreFlag.

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

```
  ~ Microsoft.RecoveryServices/vaults/BACKUP-VAULT-DEFAULT-TEST/backupStorageConfig/vaultStorageConfig [2020-02-02]
    - properties.dedupState:       "Disabled"
    - properties.storageType:      "GeoRedundant"
    - properties.storageTypeState: "Locked"
    - properties.xcoolState:       "Disabled"

```

**Additional context**

**Comment by detienne20** [comment]
w44

**Comment by alex-frankel** [comment]
This fix should be fully deployed. Let us know if you are still setting this issue.
