### ISSUE TITLE
Microsoft.RecoveryServices/vaults/backupConfig

### ISSUE THREAD

**Issue by slavizh** [Azure/arm-template-whatif#133]
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.RecoveryServices/vaults/backupConfig

**apiVersion** (i.e. 2019-04-01)
2020-02-02

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
The property is not something that can be provided for the resource.

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

```
  ~ Microsoft.RecoveryServices/vaults/BACKUP-VAULT-DEFAULT-TEST/backupConfig/vaultConfig [2020-02-02]
    - properties.isSoftDeleteFeatureStateEditable: true

```

**Additional context**

**Comment by shenglol** [comment]
[w44]?

**Comment by alex-frankel** [comment]
This fix should be fully deployed. Let us know if you are still setting this issue.
