### ISSUE TITLE
Microsoft.Network/applicationGateways probes backendHttpSettings always marked for removal

### ISSUE THREAD

**Issue by fulder** [Azure/arm-template-whatif#139]
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.Network/applicationGateways

**apiVersion** (i.e. 2019-04-01)
2019-11-01

**Client (PowerShell, Azure CLI, or API)**
Azure CLI

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**
Application Gateway templates are really long so just posting the `probes` property:
```
...
"probes":[
  {
    "id":"[concat(resourceId('Microsoft.Network/applicationGateways', parameters('gatewayName')), '/probes/myProbe')]",
    "name":"myProbe",
    "properties":{
      "protocol":"Https",
      "path":"/probe-path",
      "interval":30,
      "timeout":20,
      "unhealthyThreshold":3,
      "pickHostNameFromBackendHttpSettings":true,
      "minServers":0,
      "match":{
        "statusCodes":[
          "200"
        ]
      }
    }
  }
]
...
```

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
No noise when after this resource was deployed and not changed

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**
```
 properties.probes: [
      ~ 0:
        - properties.backendHttpSettings: [
            0:
              id: "/subscriptions/<SUB_ID>/resourceGroups/<RESOURCE_GROUP>/providers/Microsoft.Network/applicationGateways/<GATEWAY_NAME>/backendHttpSettingsCollection/myBackend"
          ]
```

**Additional context**

**Comment by fulder** [comment]
This issue looks a bit alike: https://github.com/Azure/arm-template-whatif/issues/100 although there are other properties and IDs

**Comment by smits23** [comment]
is there any update on a fixed date for this?

**Comment by shenglol** [comment]
We committed a fix and it should be deployed in 2 weeks [w47].

**Comment by alex-frankel** [comment]
This fix should be fully deployed. Please let us know if you are able to reproduce the issue.

**Comment by fulder** [comment]
Works fine for me, can no longer see this noise. Thank you for this fix :+1:
