### ISSUE TITLE
Microsoft.Insights/components (2014-04-01)

### ISSUE THREAD

**Issue by SebastianSchuetze** [Azure/arm-template-whatif#14]
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.Insights/components/RP-FA-MyTestAppTest 

**apiVersion** (i.e. 2019-04-01)
2014-04-01

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code**
```javascript
 {
      "apiVersion": "2014-04-01",
      "name": "[variables('functionAppName')]",
      "type": "Microsoft.Insights/components",
      "location": "[resourceGroup().location]",
      "tags": {
        "[concat('hidden-link:', resourceGroup().id, '/providers/Microsoft.Web/sites/', variables('functionAppName'))]": "Resource",
        "displayName": "AppInsightsComponent"
      },
      "properties": {
        "applicationId": "[variables('functionAppName')]"
      }
    }
```

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
I expected no noise since the template has not been modified since the resources were deployed

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**
![image](https://user-images.githubusercontent.com/7256168/70303558-3666e100-1800-11ea-8572-d2b03523692c.png)

**Additional context**

**Comment by majastrz** [comment]
The fixes have been committed to an internal repo and are awaiting deployment. [w18]

**Comment by SebastianSchuetze** [comment]
pls, close it if you think it's fixed.
