### ISSUE TITLE
Microsoft.AppConfiguration/configurationStores/keyValues

### ISSUE THREAD

**Issue by slavizh** [Azure/arm-template-whatif#148]
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.AppConfiguration/configurationStores/keyValues

**apiVersion** (i.e. 2019-04-01)
2020-07-01-preview

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**
Brand new RP that does not show if it will be created, updated, or ignored.

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**

Expecting to see it either as created, updated or ignored.

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

Mainly missing from What-If
Official doc was published 2 months ago: https://github.com/Azure/AppConfiguration/issues/268

**Additional context**

**Comment by alex-frankel** [comment]
Sorry, I'm not clear what's not working. Is the resource not showing up at all in the what-if response?

**Comment by slavizh** [comment]
@alex-frankel the resource does not show in what-if at all. My template is no different than https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-resource-manager
