### ISSUE TITLE
Microsoft.Web/serverfarms (2015-04-01)

### ISSUE THREAD

**Issue by SebastianSchuetze** [Azure/arm-template-whatif#15]
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.Web/serverfarms 

**apiVersion** (i.e. 2019-04-01)
2015-04-01

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object specified in #1 and #2, but if it's easier you can include the entire template**
```
{
      "type": "Microsoft.Web/serverfarms",
      "apiVersion": "2015-04-01",
      "name": "[variables('hostingPlanName')]",
      "location": "[resourceGroup().location]",
      "properties": {
        "name": "[variables('hostingPlanName')]",
        "computeMode": "Dynamic",
        "sku": "Dynamic"
      }
    }
```

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
I expected no noise since the template has not been modified since the resources were deployed

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**
![image](https://user-images.githubusercontent.com/7256168/70304099-711d4900-1801-11ea-8898-903c1e772c3b.png)

**Additional context**

**Comment by majastrz** [comment]
The fixes have been committed to an internal repo and are awaiting deployment. [w18]

**Comment by SebastianSchuetze** [comment]
pls, close it if you think it's fixed.
