### ISSUE TITLE
Link to GitHub issues in What if output is wrong

### ISSUE THREAD

**Issue by Ba4bes** [Azure/arm-template-whatif#152]
**Describe the bug**
A small detail, but in the output that What-If gives, there is a link to the issues. The point at the end of the line breaks the link.

**To Reproduce**
1. Deploy any ARM template with Whatif. Output will include these lines:
```
Getting the latest status of all resources...
                                             
What if: 
        

Note: The result may contain false positive predictions (noise).
You can help us improve the accuracy of the result by opening an issue here: https://aka.ms/WhatIfIssues.

```
2. Try to click the link https://aka.ms/WhatIfIssues.
3. It will point to https://www.microsoft.com/nl-nl/?ref=aka

**Expected behavior**
To be lead to the GitHub issue page

**Comment by alex-frankel** [comment]
Are you still able to reproduce this? When I click on the above link (https://aka.ms/WhatIfIssues) it takes me to the correct page

**Comment by Ba4bes** [comment]
Tried it again and it is now leading me to the correct link without the dot at the end.
Thank you, will close this issue 👍
