### ISSUE TITLE
Microsoft.Insights/components properties

### ISSUE THREAD

**Issue by J0F3** [Azure/arm-template-whatif#154]
## Describe the noise

**Resource type** Microsoft.Insights/component

**apiVersion**  2015-05-01

**Client: PowerShell and Azure CLI

**Relevant ARM Template code**
```
{
  "type": "Microsoft.Insights/components",
  "apiVersion": "2015-05-01",
  "name": "[variables('applicationInsightsName')]",
  "location": "[parameters('location')]",
  "kind": "web",,
  "properties": {
    "Application_Type": "web"
  }
}
```

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
no diff

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**
```
    - properties.publicNetworkAccessForIngestion: "Enabled"
    - properties.publicNetworkAccessForQuery:     "Enabled"
    + properties.Flow_Type:                       "Bluefield"
    + properties.Request_Source:                  "rest"
```

**Additional context**
`properties.Flow_Type` and  `properties.Request_Source` are documented in the ARM reference [documentation](https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/2015-05-01/components) but `properties.publicNetworkAccessForIngestion` and `properties.publicNetworkAccessForQuery ` are not even documented. (and Bicep complains about it when set: "publicNetworkAccessForQuery" is not allowed on objects of type "ApplicationInsightsComponentProperties")

**Comment by alex-frankel** [comment]
Closing as dup of #89
