### ISSUE TITLE
CosmosDB silently ignoring no-op property

### ISSUE THREAD

**Issue by mauve** [Azure/arm-template-whatif#174]
## Describe the noise

**Resource type** Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/throughputSettings

**apiVersion** 2021-03-15

**Client (PowerShell, Azure CLI, or API)** Azure CLI

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**

```bicep
resource framesContainer_throughPutSettings 'Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/throughputSettings@2021-03-15' = {
  name: 'default'
  parent: framesContainer

  properties: {
    resource: {
      throughput: 400
      autoscaleSettings: {
        maxThroughput: 4000
      }
    }
  }
}
```

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**

I expected no noise since the template has not been modified since the resources were deployed

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

```
  ~ Microsoft.DocumentDB/databaseAccounts/<REDACTED>/sqlDatabases/<REDACTED>/containers/frames/throughputSettings/default [2021-03-15]
    + properties.resource.autoscaleSettings:

        maxThroughput: 4000
```

**Additional context**

**Comment by mauve** [comment]
this turns out to be because you cannot specify both, (I thought setting both would specify min/max) only `resource.throughput` has effect so every operation has `+ resource.autoscaleSettings.maxThroughput` which is just ignored.

This should definitely be an error.

**Comment by alex-frankel** [comment]
@mauve - FWIW, if this issue is still happening, I would recommend opening a support ticket. Generally RPs do allow properties they don't know about, but it would be a better behavior to fail than let the user think it worked.

cc @markjbrown as FYI

**Comment by markjbrown** [comment]
Sorry, I'm not quite following.

If the resource is configured for autoscale you use `autoscaleSettings.maxThroughput`. If it is standard throughput, you just specify `throughput`.

All of the sample ARM/Bicep samples are written with standard and autoscale flavors. Even exported ARM templates out the correct throughput properties. The expectation is customers recognize the difference.

[ARM Samples](https://docs.microsoft.com/azure/cosmos-db/sql/templates-samples-sql)
[Bicep Samples](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/bicep-samples)

**Comment by mauve** [comment]
Thanks, I forgot to close this ticket after eventually figuring that out.

TBH, a validation error would have been a reasonable response.

**Comment by markjbrown** [comment]
@mauve yes, sure. I can add to our backlog.

Thanks.
