### ISSUE TITLE
Microsoft.EventGrid/topics/{topic}/providers/Microsoft.EventGrid/eventSubscriptions (2018-01-01)

### ISSUE THREAD

**Issue by SebastianSchuetze** [Azure/arm-template-whatif#18]
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.EventGrid/topics/{topic}/providers/Microsoft.EventGrid/eventSubscriptions

**apiVersion** (i.e. 2019-04-01)
2018-01-01

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object specified in 1 and 2, but if it's easier you can include the entire template**
```
{
            "type": "Microsoft.EventGrid/topics",
            "apiVersion": "2018-01-01",
            "name": "[parameters('eventGridTopicName')]",
            "location": "[parameters('location')]"
        },
        {
            "type": "Microsoft.EventGrid/topics/providers/eventSubscriptions",
            "apiVersion": "2018-01-01",
            "name": "[concat(parameters('eventGridTopicName'), '/Microsoft.EventGrid/', parameters('eventGridSubscriptionName'))]",
            "location": "[parameters('location')]",
            "dependsOn": [
                "[parameters('eventGridTopicName')]"
            ],
            "properties": {
                "destination": {
                    "endpointType": "WebHook",
                    "properties": {
                        "endpointUrl": "[parameters('eventGridSubscriptionUrl')]"
                    }
                },
                "filter": {
                    "includedEventTypes": [
                        "All"
                    ]
                }
            }
        }
```

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
I expected no noise since the template has not been modified since the resources were deployed

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**
![image](https://user-images.githubusercontent.com/7256168/70322423-5b704980-182a-11ea-8cd3-7516b5fba35f.png)

**Additional context**

I used the following template: https://github.com/Azure/azure-quickstart-templates/tree/master/101-event-grid

**Comment by alex-frankel** [comment]
@SebastianSchuetze - is `properties.destination.properties.endpointUrl` considered a secret?

**Comment by SebastianSchuetze** [comment]
yes @alex-frankel .Because it contains the full URL with a key which I could call directly. Since it is a webhook (in this case to a logic app) anybody could use it to do something with my logic app (or any other resource that uses webhooks).

**Comment by majastrz** [comment]
The fix for the issue with `endpointBaseUrl` and `endpointUrl` has been checked in to an internal repo and is awaiting deployment. [w25?]

**Comment by alex-frankel** [comment]
This should be fully resolved. Please let us know if you still see any issues.
