### ISSUE TITLE
CosmosDB throughput settings constant noise

### ISSUE THREAD

**Issue by mauve** [Azure/arm-template-whatif#188]
## Describe the noise

**Resource type** 

Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/throughputSettings

**apiVersion**

2021-03-15

**Client (PowerShell, Azure CLI, or API)**

`az cli`

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**

```bicep
resource framesContainer_throughPutSettings 'Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/throughputSettings@2021-03-15' = {
  name: 'default'
  parent: framesContainer

  properties: {
    resource: {
      autoscaleSettings: {
        maxThroughput: 4000
      }
    }
  }
}

```

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**

I expected no noise

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

```
  ~ Microsoft.DocumentDB/databaseAccounts/db7j7m73tk5rgxm-database/sqlDatabases/device2cloud/containers/frames/throughputSettings/default [2021-03-15]
    - properties.resource.throughput: 400
```

**Additional context**

**Comment by alex-frankel** [comment]
Closing as dup of #186
