### ISSUE TITLE
[Suggestion] Make automated tests for the cmdlet

### ISSUE THREAD

**Issue by SebastianSchuetze** [Azure/arm-template-whatif#19]
Hi,

After reporting the first noise reports. I noticed that it always has the same pattern.

1. deploy template successfully
2. use New-AzDeploymentWhatIf with the same template
3. If there are changes suggested in the output, then make a noise report.

My assumption: noise is something that the "What if" returns changes within the template even if the exact same template was used for the first deployment and is now used with a "what if" cmdlet.

## Suggestion: Design automated tests for this
How would an automated test look like:
* You deploy an ARM-Template into a resource group
* You call New-AzDeploymentWhatIf with the same template again
* if no Delete, Create or Modify statements appear then there is no noise, otherwise it is a false positive
* for false-positive: automatically log the output, the noise properties and the template somewhere so it can be looked at

## Use community power for testable templates
The community could help a lot with this:
https://github.com/Azure/azure-quickstart-templates

You could run these automated tests against the existing quickstart templates.
The only problem: many of the need to have the parameter files edited to have default values.

If a solution for the parameter files is found, then you have a vast amount of different ARM templates you could test against.

**Comment by alex-frankel** [comment]
Thanks Sebastian - we are actually well underway with automating noise identification/elimination as much as possible. We're hoping to close most of the current issues using this auto-generation by the end of next week.

And, as you note, we are using the quickstart-templates to test this continuously.

I'll close this once the automation work is implemented.

**Comment by SebastianSchuetze** [comment]
So I am running in open doors already. We have a saying for these situations in Germany: "Zwei Dumme ein Gedanke" (Two stupid ones same thought" ;-)

But glad to hear it!!

**Comment by alex-frankel** [comment]
Going to close this, as we now have the (ever-improving) pipeline wired up and have a noise generation report here:
https://github.com/Azure/arm-template-whatif/issues/38
