### ISSUE TITLE
Microsoft.Databricks/workspaces (2018-04-01)

### ISSUE THREAD

**Issue by SebastianSchuetze** [Azure/arm-template-whatif#20]
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.Databricks/workspaces

**apiVersion** (i.e. 2019-04-01)
2018-04-01

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**
```
  {
            "type": "Microsoft.Databricks/workspaces",
            "apiVersion": "2018-04-01",
            "name": "[parameters('workspaceName')]",
            "location": "westeurope",
            "sku": {
                "name": "[parameters('tier')]"
            },
            "properties": {
                "ManagedResourceGroupId": "[variables('managedResourceGroupId')]"
            }
        }
```

**Expected response**
I expected no noise since the template has not been modified since the resources were deployed

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**
![image](https://user-images.githubusercontent.com/7256168/70358793-71a5f600-187a-11ea-95a4-9b4745377b45.png)

**Additional context**
Created with the standard template over the portal GUI

**Comment by majastrz** [comment]
The fixes for `createdBy`, `updatedBy` have been committed to an internal repo. We have also fixed the property name casing issue (seen on `ManagedResourceGroupId` property in your case) for all resource types and API versions. Both fixes are awaiting deployment.

**Comment by majastrz** [comment]
The previously mentioned fixes should be deployed at this point. We are investigating the issue with `properties.parameters`.

**Comment by majastrz** [comment]
The fix has now been committed to an internal repo and is awaiting deployment. [w18]

**Comment by SebastianSchuetze** [comment]
pls, close it if you think it's fixed.
