### ISSUE TITLE
What-if with bicep does not show changes introduces by deeply nested modules 

### ISSUE THREAD

**Issue by miqm** [Azure/arm-template-whatif#201]
**Describe the bug**
running what-if when you have module that calls a module results that changes introduced by that 2nd module are not reflected.

**To Reproduce**
1. deploy main.bicep that calls moduleA
2. moduleA calls moduleB
3. moduleB deploys resources

**Expected behavior**
What-if should detect changes introduced by entire deployment, regardless how many module calls are there 

**Client** [e.g. PowerShell, CLI, API)
CLI

**Additional context**
With bicep is very easy now to nest modules. What-if should reflect that.

**Comment by sladkoff** [comment]
Note that it doesn't even have to be 'deeply nested'.

It can be reproduced with the following example where there is one 'main' bicep file **A**, which uses modules **B** and **C**. 
**B** outputs variables that **C** wants to use.

### Module A

```bicep
module B 'B.bicep' = {
  name: 'B'
}

module C 'C.bicep' = {
  name: 'C'
  params: {
    storageAccountName: B.outputs.storageAccountName
  }
}
```

### Module B

```bicep
resource storageAccount 'Microsoft.Storage/storageAccounts@2021-01-01' = {
  name: 'bstorageaccount'
  location: resourceGroup().location
  sku: {
    name: 'Standard_LRS'
    tier: 'Standard'
  }
  kind: 'StorageV2'
  properties: {
  }
}

output storageAccountName string = storageAccount.name
```

### Module C

```bicep
param storageAccountName string

resource blobServices 'Microsoft.Storage/storageAccounts/blobServices@2021-04-01' = {
  name: '${storageAccountName}/default'
  properties: {
    cors: {
      corsRules: []
    }
    deleteRetentionPolicy: {
      enabled: true
      days: 7
    }
  }
}
```

### Output

Deploying these templates will lead to the following output (Note the missing `blobServices` resource from `C.bicep`)

```bash
$ az deployment group what-if --template-file A.bicep -g my-rg
Note: The result may contain false positive predictions (noise).
You can help us improve the accuracy of the result by opening an issue here: https://aka.ms/WhatIfIssues.

Resource and property changes are indicated with these symbols:
  + Create
  * Ignore

The deployment will update the following scope:

Scope: /subscriptions/xxxxxxxxxxxx/resourceGroups/my-rg

  + Microsoft.Storage/storageAccounts/bstorageaccount [2021-01-01]

      apiVersion: "2021-01-01"
      id:         "/subscriptions/xxxxxxxxxxxx/resourceGroups/my-rg/providers/Microsoft.Storage/storageAccounts/bstorageaccount"
      kind:       "StorageV2"
      location:   "westeurope"
      name:       "bstorageaccount"
      sku.name:   "Standard_LRS"
      type:       "Microsoft.Storage/storageAccounts"

Resource changes: 1 to create, 0 to ignore.
```

A workaround for the above example is to move content from **C** to **B**. We will then see that two resources are to be created in the what-if command.

I think bicep modules are very useful! However we are currently forced to workaround the issue described here by maintaining large flat template files.

**Comment by miqm** [comment]
@alex-frankel?

**Comment by alex-frankel** [comment]
This is a dup of #157. Just so folks are aware, this is a pretty low-level issue that we need to be careful in resolving. We're trying to get it fixed before end of CY21.
