### ISSUE TITLE
Microsoft.Network/networkInterfaces vnetEncryptionSupported

### ISSUE THREAD

**Issue by johndowns** [Azure/arm-template-whatif#208]
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.Network/networkInterfaces

**apiVersion** (i.e. 2019-04-01)
2020-11-01. It doesn't happen with 2020-07-01.

**Client (PowerShell, Azure CLI, or API)**
Azure CLI. Version:

```
azure-cli                         2.24.2 *

core                              2.24.2 *
telemetry                          1.0.6

Extensions:
azure-devops                      0.18.0
resource-graph                     2.1.0
```

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**
```bicep
resource networkInterface 'Microsoft.Network/networkInterfaces@2020-11-01' = {
  name: networkInterfaceName
  location: location
  properties: {
    ipConfigurations: [
      {
        name: 'ipconfig1'
        properties: {
          privateIPAllocationMethod: 'Dynamic'
          publicIPAddress: {
            id: publicIPAddress.id
          }
          subnet: {
            id: virtualNetwork::defaultSubnet.id
          }
          primary: true
          privateIPAddressVersion: 'IPv4'
        }
      }
    ]
    enableAcceleratedNetworking: true
    enableIPForwarding: false
    networkSecurityGroup: {
      id: networkSecurityGroup.id
    }
  }
}
```

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
I expected to see the privateIPAddress change since I removed the explicit property (given the NIC is configured for dynamic allocation), but not the `vnetEncryptionSupported` property since (a) I didn't change it, and (b) it appears to be read-only (it doesn't appear on [the docs](https://docs.microsoft.com/en-us/azure/templates/microsoft.network/networkinterfaces?tabs=json).

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

```
Note: The result may contain false positive predictions (noise).
You can help us improve the accuracy of the result by opening an issue here: https://aka.ms/WhatIfIssues.

Resource and property changes are indicated with these symbols:
  - Delete
  ~ Modify
  = Nochange
  * Ignore

The deployment will update the following scope:

Scope: /subscriptions/xxx/resourceGroups/TOYTRUCK

  ~ Microsoft.Network/networkInterfaces/toytruckserver890 [2020-11-01]
    - properties.vnetEncryptionSupported: false
    ~ properties.ipConfigurations: [
      ~ 0:

        - properties.privateIPAddress: "10.0.0.4"

      ]

  = Microsoft.Compute/virtualMachines/ToyTruckServer [2021-03-01]
  = Microsoft.Network/networkSecurityGroups/ToyTruckServer-nsg [2020-11-01]
  = Microsoft.Network/publicIPAddresses/ToyTruckServer-ip [2020-11-01]
  = Microsoft.Network/virtualNetworks/ToyTruck-vnet [2020-11-01]
  * Microsoft.Compute/disks/ToyTruckServer_disk1_23e6a144c4ea4049b3e2be24b78a9e81
```

**Additional context**
This is an exported template that I'm trying to Bicepify and clean up. The exported template uses API version 2020-11-01, but when I switch to 2020-07-01 the noise goes away.

**Comment by alexmpm** [comment]
Same here! My scenario has also a NIC creation and I am always getting the "vnetEncryptionSupported" property be marked as "delete", even if I don't change if (we can't as this property is not in Bicep).
I believe this is causing my deployment to fail on a second run (first run deploys fine) as due this change, the NIC try to changed but it is already assigned to a subnet (a step in my bicep).

**Comment by christout** [comment]
Appears fixed in API version 2021-05-01.

**Comment by stephaniezyen** [comment]
Fixed as stated by above comment.
