### ISSUE TITLE
ERROR: 'NoEffect' in azure devops pipeline, inline az script from az version 2.1.1 on

### ISSUE THREAD

**Issue by pinback42** [Azure/arm-template-whatif#211]
**Describe the bug**
create an inline script in azure devops pipeline with whatIf, in our case

inlineScript: |
az deployment group what-if --name TEST-SP --resource-group TEST --template-file infrastructure/templates/app-service-plan/app-service-plan.json

if there are no changes to the SP cause it's already deployed, there is no what-of output but
ERROR: 'NoEffect'
displayed. This startet after update of azure console in pipeline from 2.1.0 to 2.1.1

**To Reproduce**

**Expected behavior**
the what-if information should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/88875409/129319708-69ecd42a-b124-4767-96e5-ba230a14262a.png)

**Client** [e.g. PowerShell, CLI, API)
InlineScript for Azure Console in azure pipeline

**Additional context**
Task         : Azure CLI
Description  : Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/PowerShell Core/Batch script when running on Windows agent.
Version      : 2.1.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
==============================================================================
/usr/bin/az --version
WARNING: You have 2 updates available. Consider updating your CLI installation with 'az upgrade'
azure-cli                         2.27.0 *
core                              2.27.0 *
telemetry                          1.0.6
Extensions:
azure-devops                      0.20.0

Python location '/opt/az/bin/python3'
Extensions directory '/opt/az/azcliextensions'

Python (Linux) 3.6.10 (default, Jul 30 2021, 11:24:27) 
[GCC 9.3.0]

**Comment by samhughes91** [comment]
I am having the exact same issues in my pipeline. I am also able to reproduce locally with a key vault resource and data factory config. Please let me know if you need me to supply more info. I'm hoping this gets fixed!

**Comment by larryclaman** [comment]
error reported here: https://github.com/Azure/azure-cli/issues/19124
I solved it by downgrading from cli 2.27.0 to 2.26.0

**Comment by samhughes91** [comment]
@larryclaman Thanks for the feedback man, much appreciated

**Comment by pinback42** [comment]
ok, now works again with latest cli 2.27.1
