### ISSUE TITLE
 Microsoft.Sql/servers/{servername}/databases (2017-10-01-preview)

### ISSUE THREAD

**Issue by SebastianSchuetze** [Azure/arm-template-whatif#22]
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
 Microsoft.Sql/servers/{servername}/databases

**apiVersion** (i.e. 2019-04-01)
2017-10-01-preview

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**
```
  {
                    "type": "databases",
                    "apiVersion": "2017-10-01-preview",
                    "name": "[parameters('databaseName')]",
                    "location": "[parameters('serverLocation')]",
                    "dependsOn": [
                        "[concat('Microsoft.Sql/servers/', parameters('serverName'))]",
                        "[concat('Microsoft.Sql/servers/', parameters('serverName'), '/elasticpools/', parameters('elasticPoolName'))]"
                    ],
                    "tags": "[parameters('databaseTags')]",
                    "properties": {
                        "collation": "[parameters('collation')]",
                        "elasticPoolId": "[resourceId('Microsoft.Sql/servers/elasticpools', parameters('serverName') , parameters('elasticPoolName'))]",
                        "sampleName": "[parameters('sampleName')]",
                        "zoneRedundant": "[parameters('zoneRedundant')]",
                        "licenseType": "[parameters('licenseType')]"
                    }
                }
```

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
I expected no noise since the template has not been modified since the resources were deployed

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**
![image](https://user-images.githubusercontent.com/7256168/70362210-6b1c7c00-1884-11ea-9f1e-3bbc488aa6ad.png)

**Additional context**
check #21 for full template

**Comment by shenglol** [comment]
Fix has been committed and is waiting on deployment. [w17]

**Comment by SebastianSchuetze** [comment]
pls, close it if you think it's fixed.

**Comment by alex-frankel** [comment]
The fix should be deployed. Please reopen the issue if you still see this noise.
