### ISSUE TITLE
Microsoft.Sql/servers/{servername}/elasticpools (2017-10-01-preview)

### ISSUE THREAD

**Issue by SebastianSchuetze** [Azure/arm-template-whatif#23]
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.Sql/servers/{servername}/elasticpools

**apiVersion** (i.e. 2019-04-01)
2017-10-01-preview

**Client (PowerShell, Azure CLI, or API)**

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**
```
 {
                    "type": "Microsoft.Sql/servers/elasticpools",
                    "apiVersion": "2017-10-01-preview",
                    "name": "[concat(parameters('serverName'), '/', parameters('elasticPoolName'))]",
                    "location": "[parameters('serverLocation')]",
                    "dependsOn": [
                        "[concat('Microsoft.Sql/servers/', parameters('serverName'))]"
                    ],
                    "tags": "[parameters('elasticPoolTags')]",
                    "sku": {
                        "name": "[parameters('skuName')]",
                        "tier": "[parameters('tier')]",
                        "capacity": "[parameters('poolLimit')]"
                    },
                    "properties": {
                        "perDatabaseSettings": {
                            "minCapacity": "[parameters('perDatabasePerformanceMin')]",
                            "maxCapacity": "[parameters('perDatabasePerformanceMax')]"
                        },
                        "zoneRedundant": "[parameters('zoneRedundant')]",
                        "licenseType": "[parameters('licenseType')]",
                        "storageMB": "[parameters('poolSize')]"
                    }
                }
```

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
I expected no noise since the template has not been modified since the resources were deployed

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**
![image](https://user-images.githubusercontent.com/7256168/70362274-b20a7180-1884-11ea-80cc-713afc2afcd6.png)

**Additional context**
Check #21 for full template

**Comment by majastrz** [comment]
@SebastianSchuetze, it appears that the `properties.storageMB` property is effectively getting renamed by the resource to `properties.maxSizeBytes`. Can you confirm this behavior? Does it happen even if you change the value?

**Comment by majastrz** [comment]
In addition, we are now normalizing number formats so changes like 5 -> "5" or 0 -> "0" should be ignored now.

**Comment by shenglol** [comment]
This one has been dangling for a while...I checked the docs for the resource type - it seems `storageMB` is not in the schema. I'll run some tests to confirm that.

**Comment by shenglol** [comment]
It turns out `storageMB` exists in older API versions, and `maxSizeBytes` is a replacement for it in newer API versions. Both of them are read-only.

**Comment by shenglol** [comment]
[w36]?

**Comment by alex-frankel** [comment]
This fix should be fully deployed. Let us know if you still see the noise.
