### ISSUE TITLE
Azure dashboard MonitorChartPart double array causes what-if ERROR: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by Thorium** [Azure/arm-template-whatif#231]
If you do an Azure dashboard and add a MonitorChartPart (to monitor resource usage like CPU, DTU, or what ever), and download it from the Azure download button, the ARM generated is like this:

![image](https://user-images.githubusercontent.com/229355/134461402-e7ef1e43-d5af-4ab8-8444-81435e939af7.png)

Now, if you run what-if on that, the ``charts = [ [ ... ] ]`` double array causes what-if to crash with:
`ERROR: object of type 'NoneType' has no len()`

This was found with Azure Cli command.

**Comment by alex-frankel** [comment]
@Thorium do you mind opening this in the [auzre/azure-cli](https://github.com/azure/azure-cli) repo? Looks like the issue is coming from there.
