### ISSUE TITLE
what-if running into timeout when SQL server key resource shall be deployed

### ISSUE THREAD

**Issue by flobeier** [Azure/arm-template-whatif#239]
**Describe the bug**
As soon as I add an SQL server key resource to my bicep file the what-if operation runs until it times out.

**To Reproduce**
1. Deploy an SQL server without an identity (via template or CLI) and a key vault independently of the bicep file.
2. Try to run the following code:
```bicep
resource sqlServer 'Microsoft.Sql/servers@2021-05-01-preview' = {
  name: serverName
  location: location
  identity: {
    type: 'SystemAssigned'
  }
}

resource keyVault 'Microsoft.KeyVault/vaults@2021-06-01-preview' existing = {
  name: keyVaultName
}

resource identityPolicy 'Microsoft.KeyVault/vaults/accessPolicies@2021-06-01-preview' = {
  name: 'add'
  parent: keyVault
  properties: {
    accessPolicies: [
      {
        tenantId: tenant().tenantId
        permissions: {
          keys: [
            'unwrapKey'
            'wrapKey'
            'get'
          ]
        }
        objectId: sqlServer.identity.principalId
      }
    ]
  }
}

resource kvKey 'Microsoft.KeyVault/vaults/keys@2021-06-01-preview' = {
  name: 'rsa-${sqlServer.name}'
  parent: keyVault
  properties: {
    keySize: 3072
    kty: 'RSA'
  }
}

resource serverKey 'Microsoft.Sql/servers/keys@2021-05-01-preview' = {
  name: 'main'
  parent: sqlServer
  properties: {
    serverKeyType: 'AzureKeyVault'
    uri: kvKey.properties.keyUri
  }
  dependsOn: [
    identityPolicy
  ]
}

resource ep 'Microsoft.Sql/servers/encryptionProtector@2021-05-01-preview' = {
  name: 'current'
  parent: sqlServer
  properties: {
    autoRotationEnabled: true
    serverKeyName: serverKey.name
    serverKeyType: 'AzureKeyVault'
  }
}
```

**Expected behavior**
what-if shows what will be deployed.

**Actual behavior**
what-if operation times out. When the server key resource is removed from the deployment it doesn't time out.

**Client**
Azure CLI 2.30.0 (Cloud Shell)

**Additional context**
```log
Diagnostic information: timestamp '20211202T212149Z', tracking id 'b024686a-ad20-4133-ae54-172ec4d0e664', request correlation id 'ccf470f5-2ee7-46e4-b8d8-9207dc2c54f8', location 'westeurope'.
```

**Comment by flobeier** [comment]
Update: Not only does the what-if operation run into a timeout but also the deployment when I try to deploy the resources. So this issue appears to be not only related to what-if.

**Comment by flobeier** [comment]
Alright, through trial and error I was able to figure out the following:
1. The server key uri needs `kvKey.properties.keyUriWithVersion` instead of `kvKey.properties.keyUri`. Changing that made what-if work and the deployment doesn't run into a timeout anymore but fails with an "Internal Server Error" (HTTP 500).
2. The name of the server key apparently needs to be in the format `<keyvault name>_<key name>_<key version>`. If this format is used, the deployment is successful, every other name leads to an internal server error. This is not documented (see the [documentation](https://docs.microsoft.com/en-us/azure/templates/microsoft.sql/servers/keys?tabs=bicep)), I just had a look what the Azure Portal configures when setting up TDE for an SQL server with a customer-managed key. I'm still not entirely sure that my finding is correct because it's a bit strange but that's how it looks to me right now. To verify my hypothesis I rotated the key, used a key name without the suffix `_<new key version>` first (deployment failed) and then with the suffix (deployment was successful).

@alex-frankel since this is not entirely what-if related, shall I open another issue somewhere? If yes, can you point me to the right place?

**Comment by alex-frankel** [comment]
The best thing to do for this issue would be to open a support case with the Key Vault team. Any 500 / Internal Server Error is a bug in the error-handling logic of the relevant resource provider. This most recent response should provide enough info to the support team, but they may also want to see Correlation IDs for any failed deployments.

Going to close this for now, but feel free to keep this thread updated.

**Comment by flobeier** [comment]
Thanks for your help! I'll create an issue with the SQL Server team then because it's their resource provider that is responsible for the issue (`Microsoft.Sql/servers/keys` is the problematic resource).
