### ISSUE TITLE
Resource group deployment counts API version as change

### ISSUE THREAD

**Issue by slavizh** [Azure/arm-template-whatif#27]
## Describe the noise

I am deploying resource group with version 2019-07-01 but What-If detects that there is change in the API version although there is not.

Example:

```
  ~ resourceGroups/monitoring-core-accp-stan [2019-07-01]
    ~ apiVersion: "2019-07-01" => "2019-05-01"

```

More information is provided in e-mail.

**Resource type** (i.e. Microsoft.Storage/storageAccounts)

**apiVersion** (i.e. 2019-04-01)

**Client (PowerShell, Azure CLI, or API)**

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

**Additional context**

**Comment by majastrz** [comment]
@slavizh, I'm not able to reproduce the issue. We made some fixes in this area to address the other issue you reported with duplicate resources being returned. Do you still see this problem happening with your templates?

**Comment by slavizh** [comment]
Can be closed. Seems it is solved now.
