### ISSUE TITLE
Microsoft.Insights/components Flow_Type and Request_Source properties create false positive

### ISSUE THREAD

**Issue by DanielDLHG** [Azure/arm-template-whatif#276]
## Describe the noise
False positive for create of application insights properties "properties.Flow_Type" and "properties.Request_Source"
![image](https://user-images.githubusercontent.com/65647535/184303224-38b315eb-2425-436e-8865-7520c1aa8874.png)

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.Insights/components

**apiVersion** (i.e. 2019-04-01)
2020-02-02

**Client (PowerShell, Azure CLI, or API)**
Azure CLI

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**
```
resource applicationInsights 'Microsoft.Insights/components@2020-02-02' = {
  name: applicationInsightsName
  location: location
  kind: 'web'
  properties: {
    Application_Type: 'web'
  }
  tags: tags
}
```
**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
I expected no noise since the template has not been modified since the resources were deployed

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**
Create

**Additional context**

**Comment by alex-frankel** [comment]
Closing as dup of #154
