### ISSUE TITLE
InvalidEndpointAssociationName error when creating dataCollectionRuleAssociations and specifying dataCollectionEndpointId

### ISSUE THREAD

**Issue by sanderrhorst** [Azure/arm-template-whatif#282]
**Describe the bug**
I am creating an dataCollectionRuleAssociations using terraforms resource 'azurerm_resource_group_template_deployment' and the ARM template that is described [here](https://learn.microsoft.com/en-us/azure/templates/microsoft.insights/datacollectionruleassociations?pivots=deployment-language-arm-template#datacollectionruleassociationproxyonlyresourceproperties-2).

When I don't specify the dataCollectionEndpointId, it will be empty and the association with the data collection endpoint is not created. But I do want to specify this, to make the association with the data collection enpoint as well. But when I do that, the deployment fails with the following error message:

`{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"InvalidEndpointAssociationName","message":"An association of data collection endpoint must be named 'configurationAccessEndpoint'."}]}`

**To Reproduce**
1. Create an data collection rule and a data collection endpoint
2. Create a virtual machine
3. Create a dataCollectionRuleAssociation with the ARM template that is described [here](https://learn.microsoft.com/en-us/azure/templates/microsoft.insights/datacollectionruleassociations?pivots=deployment-language-arm-template#datacollectionruleassociationproxyonlyresourceproperties-2)

**Expected behavior**
This ARM template deployment should create the association with the data collection rule and the data collection endpoint.

**Screenshots**
Not applicable

**Client** [Terraform, API)

**Additional context**
My code:

**Terraform resource:**
`resource "azurerm_resource_group_template_deployment" "data_collection_rule_association" {
  name                         = "data_collection_rule_association_${var.vm_name}"
  resource_group_name          = var.rg_name
  deployment_mode              = "Incremental"
  template_content             = file("${path.module}/arm_templates/dataCollectionRuleAssociation.json")
  parameters_content           = jsonencode({
    "vmName"                   = { value = var.vm_name }
    "associationName"          = { value = "data_collection_rule_association_${var.vm_name}" }
    "dataCollectionRuleId"     = { value = var.data_collection_rule_id }
    "dataCollectionEndpointId" = { value = var.data_collection_endpoint_id }
  })
}`

**ARM Template:**
`{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "vmName": {
      "type": "string",
      "metadata": {
        "description": "The name of the virtual machine."
      }
    },
    "associationName": {
      "type": "string",
      "metadata": {
        "description": "The name of the association."
      }
    },
    "dataCollectionRuleId": {
      "type": "string",
      "metadata": {
        "description": "The resource ID of the data collection rule."
      }
    },
    "dataCollectionEndpointId": {
      "type": "string",
      "metadata": {
        "description": "The resource ID of the data collection endpoint."
      }
    }
  },
  "resources": [
    {
      "type": "Microsoft.Insights/dataCollectionRuleAssociations",
      "apiVersion": "2021-09-01-preview",
      "scope": "[format('Microsoft.Compute/virtualMachines/{0}', parameters('vmName'))]",
      "name": "[parameters('associationName')]",
      "properties": {
        "description": "Association of data collection rule. Deleting this association will break the data collection for this virtual machine.",
        "dataCollectionRuleId": "[parameters('dataCollectionRuleId')]",
        "dataCollectionEndpointId": "[parameters('dataCollectionEndpointId')]"
      }
    }
  ]
}`

**Comment by tdrimmelen** [comment]
+1

**Comment by RikGr** [comment]
Hi Sander I fixed this by literally naming the association 'configurationAccessEndpoint' for the endpoint association. I also had to create a separate association for the Data Collection Rule association.

In BICEP it looks like:
![image](https://user-images.githubusercontent.com/12409333/191758856-352dbe5f-390b-41c6-b625-ff85037cc42e.png)


Hope this helps

**Comment by sanderrhorst** [comment]
@RikGr,

Thanks for your reply. This is really helpfull!!

I have edited my module for the dataCollectionRuleAssociation and it worked.

For everyone that wants to achieve this using terraform, this is my code:

**dataCollectionEndpointAssociation.json (ARM template within terraform module)**
`{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "vmName": {
      "type": "string",
      "metadata": {
        "description": "The name of the virtual machine."
      }
    },
    "associationName": {
      "type": "string",
      "metadata": {
        "description": "The name of the association."
      }
    },
    "dataCollectionEndpointId": {
      "type": "string",
      "metadata": {
        "description": "The resource ID of the data collection endpoint."
      }
    }
  },
  "resources": [
    {
      "type": "Microsoft.Insights/dataCollectionRuleAssociations",
      "apiVersion": "2021-09-01-preview",
      "scope": "[format('Microsoft.Compute/virtualMachines/{0}', parameters('vmName'))]",
      "name": "[parameters('associationName')]",
      "properties": {
        "description": "Association of data collection endpoint with the VM. Deleting this association will break the data collection for this virtual machine.",
        "dataCollectionEndpointId": "[parameters('dataCollectionEndpointId')]"
      }
    }
  ]
}`

**dataCollectionRuleAssociation.json (ARM template within terraform module)**
`{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "vmName": {
      "type": "string",
      "metadata": {
        "description": "The name of the virtual machine."
      }
    },
    "associationName": {
      "type": "string",
      "metadata": {
        "description": "The name of the association."
      }
    },
    "dataCollectionRuleId": {
      "type": "string",
      "metadata": {
        "description": "The resource ID of the data collection rule."
      }
    }
  },
  "resources": [
    {
      "type": "Microsoft.Insights/dataCollectionRuleAssociations",
      "apiVersion": "2021-09-01-preview",
      "scope": "[format('Microsoft.Compute/virtualMachines/{0}', parameters('vmName'))]",
      "name": "[parameters('associationName')]",
      "properties": {
        "description": "Association of data collection rule with the VM. Deleting this association will break the data collection for this virtual machine.",
        "dataCollectionRuleId": "[parameters('dataCollectionRuleId')]"
      }
    }
  ]
}`

**main.tf (within terraform module)**
`resource "azurerm_resource_group_template_deployment" "data_collection_rule_association" {
  name                         = "data_collection_rule_association_${var.vm_name}"
  resource_group_name          = var.rg_name
  deployment_mode              = "Incremental"
  template_content             = file("${path.module}/arm_templates/dataCollectionRuleAssociation.json")
  parameters_content           = jsonencode({
    "vmName"                   = { value = var.vm_name }
    "associationName"          = { value = "data_collection_rule_association_${var.vm_name}" }
    "dataCollectionRuleId"     = { value = var.data_collection_rule_id }
  })
}

resource "azurerm_resource_group_template_deployment" "data_collection_endpoint_association" {
  name                         = "data_collection_endpoint_association_${var.vm_name}"
  resource_group_name          = var.rg_name
  deployment_mode              = "Incremental"
  template_content             = file("${path.module}/arm_templates/dataCollectionEndpointAssociation.json")
  parameters_content           = jsonencode({
    "vmName"                   = { value = var.vm_name }
    "associationName"          = { value = "configurationAccessEndpoint" }
    "dataCollectionEndpointId" = { value = var.data_collection_endpoint_id }
  })
}`

**Module call (Terraform)**
`module "data_collection_rule_association_MACHINENAME" {
  source = "./monitoring/data_collection_rule_association"

  vm_name = azurerm_windows_virtual_machine.MACHINENAME.name
  rg_name = azurerm_resource_group.RG_NAME.name
  
  data_collection_rule_id     = data.azurerm_monitor_data_collection_rule.performance_metrics_windows_vms.id
  data_collection_endpoint_id = data.azurerm_monitor_data_collection_endpoint.dce_shared.id
}`

Please let me know if you have any questions!
