### ISSUE TITLE
Protected settings are shown in plaintext for the output on Microsoft.Compute/virtualMachines/extensions

### ISSUE THREAD

**Issue by brwilkinson** [Azure/arm-template-whatif#29]
**Describe the bug**
Protected settings are shown in the output on Microsoft.Compute/virtualMachines/**extensions**

**To Reproduce**
Any VM extension that has protected settings.

See image:

![image](https://user-images.githubusercontent.com/3605266/70756402-4cd5d680-1cf1-11ea-9b36-88d7320c3381.png)

https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/2019-07-01/virtualmachines/extensions

--> https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/2019-07-01/virtualmachines/extensions#virtualmachineextensionproperties-object

![image](https://user-images.githubusercontent.com/3605266/70756504-98888000-1cf1-11ea-95a4-e1830036044a.png)

Sample of output where secret is shown.

![image](https://user-images.githubusercontent.com/3605266/70756578-c8d01e80-1cf1-11ea-9f63-c4ab1730ca38.png)

similar issue to #4 

**Expected behavior**
Protected settings should be obfuscated.

**Comment by majastrz** [comment]
We will be masking `protectedSettings` in VM and VMSS extensions from now on. The fix has been committed to an internal repo and is awaiting deployment.

**Comment by brwilkinson** [comment]
Nice one. :blush:

**Comment by majastrz** [comment]
The fix for the reported issue has been deployed to all public regions. @brwilkinson, can you confirm that it's working?

In the course of the validation on my end, I discovered that VMSS lets you specify protectedSettings on Microsoft.Compute/virtualMachineScaleSets resources as well. The fix for that is coming :)

**Comment by majastrz** [comment]
Closing the issue. Please reopen if needed.
