### ISSUE TITLE
Confusing / unclear -nameFromTemplate parameter

### ISSUE THREAD

**Issue by neumanndaniel** [Azure/arm-template-whatif#3]
### Issue
I tried to run the following command to test the new `New-AzDeploymentWhatIf` cmdlet.

```
New-AzDeploymentWhatIf -ScopeType ResourceGroup -ResourceGroupName aks -TemplateFile ./aks.json -TemplateParameterFile ./aks.parameters.json -Verbose
```

I got the error message that I shall provide `-nameFromTemplate` parameter.

Running the command `New-AzDeploymentWhatIf -ScopeType ResourceGroup -ResourceGroupName aks -TemplateFile ./aks.json -TemplateParameterFile ./aks.parameters.json -nameFromTemplate akstestwhatif -Verbose` succeeded.

But I was confused that `-nameFromTemplate` overrides the value of the `name` parameter I am using in my template and template parameter file to specify the name of the AKS cluster. `azst-aks-demo` in that particular case.

```
Note: As What-If is currently in preview, the result may contain false positive predictions (noise).
You can help us improve the accuracy of the result by opening an issue here: https://aka.ms/WhatIfIssues.

Resource and property changes are indicated with these symbols:
  + Create
  * Ignore

The deployment will update the following scope:

Scope: /subscriptions/REDACTED/resourceGroups/aks

  + Microsoft.ContainerService/managedClusters/akstestwhatif

      apiVersion:                                                               "2019-08-01"
      id:
"/subscriptions/REDACTED/resourceGroups/aks/providers/Microsoft.ContainerService/managedClusters/akstestwhatif"
      location:                                                                 "northeurope"
      name:                                                                     "akstestwhatif"
```

### What to expect?

Get rid of `-nameFromTemplate` parameter or adjust the documentation to clearly point out which use case this parameter covers.

**Comment by alex-frankel** [comment]
I don't think that is coming from the WhatIf cmdlet. It looks like that is a dynamic parameter based on what is declared in the template. Is it possible that parameter is declared in the template but a value is not specified in the params file?

**Comment by neumanndaniel** [comment]
@alex-frankel You are correct that this is not coming as parameter from the WhatIf cmdlet. 

But I have the parameter `name` in the template and as well a value for it in the template parameter file. So, the question is why the WhatIf cmdlet cannot get the value for `name`?

**Comment by alex-frankel** [comment]
Can you share the template and params file? I'd like to repro and experiment with this. Are you seeing this in the deployment ps cmdlet as well? How about Az CLI?

**Comment by alex-frankel** [comment]
@Tiano2017 @shenglol fyi

**Comment by neumanndaniel** [comment]
> Can you share the template and params file? I'd like to repro and experiment with this. Are you seeing this in the deployment ps cmdlet as well? How about Az CLI?

Neither `New-AzDeployment` nor `New-AzResourceGroupDeployment` works. I am asked for the  `nameFromTemplate` parameter in both cases.

Azure CLI just works.

@alex-frankel I send the template and params file via email to you.

**Comment by shenglol** [comment]
Investigating.

**Comment by alex-frankel** [comment]
Unfortunately this is just a very old powershell deployment cmdlet issue:
https://github.com/Azure/azure-powershell/issues/2278

We're going to triage this and see if we can get it fixed regardless, but am going to close this particular one as it is a duplicate and not directly related to the what-if cmdlet.
