### ISSUE TITLE
The term 'New-AzDeploymentWhatIf' is not recognized as the name of a cmdlet, function, script file, or operable program

### ISSUE THREAD

**Issue by kagarlickij** [Azure/arm-template-whatif#30]
I'm trying to prepare my environment for using `New-AzDeploymentWhatIf`, but can't make it run both on my Mac with PowerShell Az version 3.3.0 and 4.0.2-preview:
https://prnt.sc/qrwhoz
..and Azure Cloud Shell (PowerShell Az version is also 3.3.0):
https://prnt.sc/qrwf4w

**Comment by alex-frankel** [comment]
What-If is in private preview, so the cmdlets are not part of Az for either powershell or CLI. You can request access to it here: https://aka.ms/armtemplatepreviews
