### ISSUE TITLE
What-If deployment fails, but deployment works as expected.

### ISSUE THREAD

**Issue by tobvil** [Azure/arm-template-whatif#300]
**Describe the bug**
We have an ADO pipeline that's been running for a while suddenly starting to fail. The pipeline has two stages. Validate and deploy.
Validate is basically just: "az deployment group what-if"
Deploy is: "az deployment group create"

We've found that it's only the whatif deployment thats fails, but actual deployment works as expected.

The template is a deploymentscript that gets existing subnets in a virtual network. Outputs the subnets as an array.
The output is then used a parameter for the virtual network deployment. 

The whatif error is: "InvalidTemplate - Deployment template validation failed: 'Template parameter 'subnets' was provided an invalid value. Expected a value of type 'Array', but received a value of type 'String'. Please see https://aka.ms/arm-create-parameter-file for usage details.'."

The output from the deploymentscript is speified as an array, and the parameter on the virtual network deployment is also an array. 

**To Reproduce**
1. Run "az deployment group what-if --name 'test' --resource-group 'rg-test' --template-file template.json --parameters location='westeurope' --parameters addressPrefixes='["192.168.0.0/24"]' --parameters location='westeurope' --parameters servicePrincipalId='123' --parameters servicePrincipalKey='123' --parameters servicePrincipalTenantId='123' --parameters subscriptionId='1234-1234-1234-1234' --parameters firewallPrivateIp='192.168.0.1' --parameters virtualNetworkName='vnet-test' --parameters resourceGroupName='rg-test'"
2. This will fail with "InvalidTemplate - Deployment template validation failed: 'Template parameter 'subnets' was provided an invalid value. Expected a value of type 'Array', but received a value of type 'String'. Please see https://aka.ms/arm-create-parameter-file for usage details.'."
3. "az deployment group create --name 'test' --resource-group 'rg-test' --template-file template.json --parameters location='westeurope' --parameters addressPrefixes='["192.168.0.0/24"]' --parameters location='westeurope' --parameters servicePrincipalId='123' --parameters servicePrincipalKey='123' --parameters servicePrincipalTenantId='123' --parameters subscriptionId='1234-1234-1234-1234' --parameters firewallPrivateIp='192.168.0.1' --parameters virtualNetworkName='vnet-test' --parameters resourceGroupName='rg-test'"
4. This will work as expected

**Expected behavior**
If the deployment is successful, i would expect the whatif to be successful as well.

**Client** [e.g. PowerShell, CLI, API)
Azure CLI

ARM template in question:
https://gist.github.com/tobvil/99b03b1d6bc8cb76cd704e7c23ecc0a3

**Comment by alex-frankel** [comment]
Closing as dup of https://github.com/Azure/bicep/issues/9854
