### ISSUE TITLE
Alert rule is reported for creation although it is already there

### ISSUE THREAD

**Issue by slavizh** [Azure/arm-template-whatif#33]
**Describe the bug**
Alert rule is reported for creation although it is already there

```
 + Microsoft.Insights/activityLogAlerts/Advisor Recommendations [2017-04-01]

      apiVersion:             "2017-04-01"
      id:                     "/subscriptions/<>/resourceGroups/<>/providers/Microsoft.Insights/activityLogAlerts/Advisor Recommendations"
      location:               "Global"
      name:                   "Advisor Recommendations"
      properties.actions.actionGroups: [
        0:

          actionGroupId: "/subscriptions/<>/resourceGroups/<>/providers/Microsoft.Insights/actionGroups/test"

      ]
      properties.condition.allOf: [
        0:

          equals: "Recommendation"
          field:  "category"

        1:

          equals: "Microsoft.Advisor/recommendations/available/action"
          field:  "operationName"

      ]
      properties.description: ""
      properties.enabled:     true
      properties.scopes: [
        0: "/subscriptions/<>"
      ]
      type:                   "Microsoft.Insights/activityLogAlerts"
```

![image](https://user-images.githubusercontent.com/11890856/74239545-bae24e00-4ce0-11ea-9444-cf6a0539e8a2.png)

Strangely I have a few other activity log alerts in that deployment and they are reported without change but this one is reported for creation.

**Comment by majastrz** [comment]
@slavizh, do you have spaces in the names of the alerts that are working correctly? Is there anything that jumps out at you that makes this rule different?

**Comment by slavizh** [comment]
Nothing significant as difference:

![image](https://user-images.githubusercontent.com/11890856/74309030-72737080-4d72-11ea-9924-b70c1422f872.png)

API is the same. The other alerts are with white spaces in the name as well. The main difference is the properties.condition. I can provide the templates in e-mail if needed.

**Comment by alex-frankel** [comment]
It would be great if you could email us the template - thanks as always Stan!

**Comment by majastrz** [comment]
Indeed. It'll be great to take a look at the template.

**Comment by majastrz** [comment]
On an email thread @slavizh mentioned that this is no longer happening. I will close the issue for now, but feel free to reopen if this happens again.
