### ISSUE TITLE
Location parameter required but not accepted

### ISSUE THREAD

**Issue by yobyot** [Azure/arm-template-whatif#37]
**Describe the bug**
According to `Get-Help New-AzDeploymentWhatIf -Detailed`, a location parameter is required. However, specifying it as input to the cmdlet produces a `Parameter set cannot be resolved using the specified named parameters` error.

**To Reproduce**
1. Issue `New-AzDeploymentWhatIf` specifying `-Location`

**Expected behavior**
`New-AzDeploymentWhatIf` should accept a required parameter.

**Screenshots**
Here's the output of `Get-Help` and the results of running the cmdlet both with and without specifying `-Location`
![2020-02-18_14-41-16](https://user-images.githubusercontent.com/14332263/74772334-c643f500-525d-11ea-81e9-09d4ce224bf5.png)

**Client** [e.g. PowerShell, CLI, API)
Windows 10 Enterprise, 1809 with Windows PowerShell 5.1.
`
PSVersion                      5.1.17763.1007
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1007
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
`

**Additional context**
This could be a newbie error -- this is my first attempt at using `New-AzDeploymentWhatIf`

**Comment by majastrz** [comment]
For what-if at resource group scope, the `-Location` parameter should not be required. For what-if at subscription scope, `-Location` parameter is required.

@shenglol, have you seen this before? `locationFromTemplate`  in the screenshot is not a cmdlet parameter, but I wonder if it's a missing template parameter or something else is going on here.

@yobyot, we are currently working on a new version of this cmdlet that redesigns the parameters to make the `Get-Help` output more clear and to make tab completion work better as well.

**Comment by yobyot** [comment]
@shenglol No, "locationFromTemplate" is _not_ a parameter in the input template. I can send you the parameter and template files separately, if you like but cannot post them here.

**Comment by alex-frankel** [comment]
Hi Alex,

Can you send me the template and params file to alfran@microsoft.com? I've also seen an issue where we autogen a required param called `nameFromTemplate` in the case of a name parameter being used in the template. I would have guessed this is what is happening if there is a `location` param in your template, but obviously that is not the case here so we should take a closer look.

FWIW, as Marcin notes, we are refactoring the cmdlets as the parameters sets are confusing. We will be going to back for separate cmdlets for each scope, and to trigger WhatIf we are going to use the -WhatIf and -Confirm powershell behaviors. So the new calls will look like:

New-AzGroupDeployment ... -WhatIf
New-AzSubscriptionDeployment ... -WhatIf
...

So this non-required location issue should go away.

**Comment by shenglol** [comment]
Pretty sure this is related to: https://github.com/Azure/azure-powershell/issues/2278, which is already fixed in Az 3.2.0. We are going to release a new alpha version of Az.Resources soon with the fix.

**Comment by shenglol** [comment]
@yobyot Do you mind checking if the issue goes away? We have include the fix for it in alpha5.

**Comment by yobyot** [comment]
@shenglol The `New-AzDeploymentWhatIf` form was remove in alpha 5 in favor of the `-WhatIf` parameter of `New-AzDeployment`, correct? If that's the case -- and I couldn't find the older cmdlet name in alpha 5, this issue didn't recur when I tested it today. Also, I quickly checked the output of `Get-Help New-AzResourceGroupDeployment` and it does not require a `-Location` parameter, which was my initial concer.

Thanks.

**Comment by alex-frankel** [comment]
Looks like this fixes the issue, so I am going to close.
