### ISSUE TITLE
What if validation shows ignore when referencing nested properties on module outputs

### ISSUE THREAD

**Issue by javierdelascasas** [Azure/arm-template-whatif#385]
**Bicep version**
0.32.4 (az bicep version)
**Describe the bug**
What if validation shows * (ignore) on resource when we use another module's output if the output tries to access a nested property.

**To Reproduce**
Create a Module A that have an output of a nested property (resource.properties.someProperty)
Call the module in main.bicep and use the output from the first module as a parameter in a second module.
The property needs to be used in a resource definition on the second module.
Run a What If on the bicep deployment. 

**Additional context**
We have seem some unexpected behaviour running "what if" validations on our bicep modules.
As an example, we have a Module A which contains a resource definition for an user-assign-identity. Inside the module we have 2 outputs:
- id = resource.id
- principalId = resource.properties.principalId

We call this Module A on our main.bicep and try to insert the output as a parameter in another Module B.
While the direct property id works well and appear to be resolved for validation (the validation shows if the resource is unaffected or updating) the principalId output does not appear to resolve for validation and no matter how many changes the resource definition have, on validation the resource appear with a * = ignore flag.

We have seen this issue everytime we try to access an output from a nested property inside a resource properties.

**Comment by jeskew** [comment]
There is a fix in private preview, but wider rollout is currently blocked due to holiday deployment freezes. Please see the linked issue for more details.
