### ISSUE TITLE
microsoft.resources/deploymentscripts (2019-10-01-preview)

### ISSUE THREAD

**Issue by alex-frankel** [Azure/arm-template-whatif#41]
**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**
https://github.com/alex-frankel/VbDemos/blob/master/deployment-script-create-cert-uri.json

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
The only property that was actually updates was `forceUpdateTag`

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**
![image](https://user-images.githubusercontent.com/11078275/79521601-6a53dd80-800e-11ea-8f9a-bb1a83bddf33.png)

**Additional context**

**Comment by alex-frankel** [comment]
All of these except for containerSettings are readOnly. containerSettings is a defaultValue I think, but lei will know :)

**Comment by majastrz** [comment]
The fix that marked `properties.outputs` and `properties.status` as read only was already committed to an internal repo and is awaiting deployment. [w15]

**Comment by majastrz** [comment]
The fix for `restartPolicy` was also checked in to an internal repo and is awaiting deployment. [2416]

**Comment by alex-frankel** [comment]
The fix should be deployed. Please reopen the issue if you still see this noise.
