### ISSUE TITLE
web/site (2018-11-01) that uses containers exposes acr password, app settings shows as create

### ISSUE THREAD

**Issue by alex-frankel** [Azure/arm-template-whatif#42]
**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**
https://github.com/anthony-c-martin/arm-templator-transpiler/blob/alex/examples/container-appsvc-sql/web-stack.json

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
appSettings were not changed, but show up as being created and expose password to container registry

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**
![image](https://user-images.githubusercontent.com/11078275/79596560-a2eaca00-8095-11ea-88c2-4a102c08d946.png)

**Comment by majastrz** [comment]
Fix has been committed to an internal repo and is awaiting deployment. [w17]

**Comment by alex-frankel** [comment]
The fix should be deployed. Please reopen the issue if you still see this noise.
