### ISSUE TITLE
Microsoft.Web/certificates (2019-08-01)

### ISSUE THREAD

**Issue by smokedlinq** [Azure/arm-template-whatif#50]
## Describe the noise
Showing a read-only? property change as well as a property change that hasn't changed.

**Resource type** (i.e. Microsoft.Storage/storageAccounts)

**apiVersion** (i.e. 2019-04-01)
2019-08-01

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**

```json
    {
      "condition": "[variables('uiUseHostname')]",
      "name": "[variables('uiHostname')]",
      "type": "Microsoft.Web/certificates",
      "apiVersion": "2019-08-01",
      "location": "[resourceGroup().location]",
      "dependsOn": [
        "[resourceId('Microsoft.Web/sites/hostnameBindings', variables('uiName'), variables('uiHostname'))]"
      ],
      "tags": "[variables('tags')]",
      "properties": {
        "canonicalName": "[variables('uiHostname')]",
        "hostNames": [
          "[variables('uiHostname')]"
        ],
        "serverFarmId": "[resourceId('Microsoft.Web/serverFarms', variables('uiPlanName'))]"
      }
    }
```

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**

No changes.

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

```
~ Microsoft.Web/certificates/mycertificate.site.com [2019-08-01]

    - properties.webSpace:     "uiServerFarm-EastUSwebspace"
    + properties.serverFarmId: "/subscriptions/{subscriptionId}/resourceGroups/myResourceGroup/providers/Microsoft.Web/serverFarms/uiServerFarm"
```

**Additional context**

**Comment by shenglol** [comment]
[w20].

**Comment by alex-frankel** [comment]
This fix should be fully deployed. Please let us know if you still see this issue.
