### ISSUE TITLE
Microsoft.Web/sites (2018-11-01)

### ISSUE THREAD

**Issue by smokedlinq** [Azure/arm-template-whatif#52]
## Describe the noise
Showing siteConfig options being new but they are already set.

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.Web/sites

**apiVersion** (i.e. 2019-04-01)
2018-11-01

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**

```json
    {
      "name": "[variables('uiName')]",
      "type": "Microsoft.Web/sites",
      "apiVersion": "2018-11-01",
      "location": "[resourceGroup().location]",
      "tags": "[variables('tags')]",
      "dependsOn": [
        "[resourceId('Microsoft.Web/serverfarms', variables('uiPlanName'))]"
      ],
      "properties": {
        "serverFarmId": "[resourceId('Microsoft.Web/serverfarms', variables('uiPlanName'))]",
        "httpsOnly": true,
        "clientAffinityEnabled": false,
        "siteConfig": {
          "webSocketsEnabled": true,
          "alwaysOn": true,
          "httpLoggingEnabled": true,
          "detailedErrorLoggingEnabled": true,
          "logsDirectorySizeLimit": "[parameters('WEBSITE_HTTPLOGGING_SIZE_LIMIT_MB')]",
          "ftpsState": "FtpsOnly",
          "http20Enabled": true
        }
      }
    }
```

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
No changes made but new properties being reported.

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

```
~ Microsoft.Web/sites/mysitename [2018-11-01]
    + properties.siteConfig:

        alwaysOn:                    true
        detailedErrorLoggingEnabled: true
        ftpsState:                   "FtpsOnly"
        http20Enabled:               true
        httpLoggingEnabled:          true
        logsDirectorySizeLimit:      128
        webSocketsEnabled:           true
```

**Additional context**

**Comment by alex-frankel** [comment]
I believe this will be fixed once the fix for https://github.com/Azure/arm-template-whatif/issues/42 is rolled out. @shenglol and @majastrz can double check that

**Comment by shenglol** [comment]
A deployment containing the fix is in progress. [w17]

**Comment by alex-frankel** [comment]
The fix should be deployed. Please reopen the issue if you still see this noise.
