### ISSUE TITLE
CLI/Feature request: --hide-ignored flag

### ISSUE THREAD

**Issue by audunsolemdal** [Azure/arm-template-whatif#53]
I run a nested subscription level template for my entire subscription, with a "main" arm template creating RG's and calling upon resource-group level templates.

using `az deployment sub what-if` works fine, but we have disks and snapshots created from services in AKS which should be ignored. In the hundreds. I can't see any flag. Not sure if using --query is possible, for this. the command docs state that "json" output is default, but my output does not remind me of json, hard to query..

**Client** [e.g. PowerShell, CLI, API)

Windows 10 1909
CLI version 2.5.1

**Comment by alex-frankel** [comment]
It is a good suggestion. We will see if we can add this. To get the raw JSON response, you can use this command:

`az deployment sub what-if --no-pretty-print`

**Comment by majastrz** [comment]
@solomson do you want to exclude resources from what-if output that match some query that you specify or is it enough just to exclude resources that what-if marks as "Ignore"?

**Comment by solomson** [comment]
Ideally as a flag, I think it is a common enough use-case.

**Comment by shenglol** [comment]
The feature will be available in the next Az CLI release. We implemented a generate parameter `--exclude-change-types / -x` so you can hide other change types, e.g.:
```bash
az deployment group what-if ... -x ignore nochange
```

**Comment by alex-frankel** [comment]
This feature has been released. Thanks for the suggestion!
