### ISSUE TITLE
Microsoft.Insights/workbooks

### ISSUE THREAD

**Issue by slavizh** [Azure/arm-template-whatif#57]
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.Insights/workbooks

**apiVersion** (i.e. 2019-04-01)
2018-06-17-preview

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
The below properties are reported as change/delete

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

```
 ~ Microsoft.Insights/workbooks/603c8485-50b1-54a3-b5d7-919ee52d632b [2018-06-17-preview]
    - properties.timeModified: "2020-05-13T12:38:39.6976932Z"
    - properties.userId:       "10032000962af628"
    - tags.hidden-title:       "Event Hubs Metrics (lz-event-hubs-monitoring)"
    ~ properties.sourceId:     "azure monitor" => "Azure Monitor"


```

**Additional context**

**Comment by shenglol** [comment]
[w33]?

**Comment by alex-frankel** [comment]
This fix should be deployed

**Comment by slavizh** [comment]
@alex-frankel Could you re-open. I see some issues still. I do not know how the tag below is applied but it is either trough portal or may be when displayName is provided in the properties the resource automatically adds it as tag as well. sourceId is clearly what-if noise reported earlier but not fixed.

```
 ~ Microsoft.Insights/workbooks/17310c96-6593-5092-ac0b-0b485eae1213 [2018-06-17-preview]
    - tags.hidden-title:   "Azure Data Factory Analytics (lz-data-factory-monitoring)"
    ~ properties.sourceId: "azure monitor" => "Azure Monitor"

```


There could be some issue with the process for fixing this as it was reported as fixed but it was not completely so may be some functional tests by the teams are needed.

**Comment by shenglol** [comment]
The fix was already deployed.
