### ISSUE TITLE
Microsoft.EventHub/namespaces

### ISSUE THREAD

**Issue by slavizh** [Azure/arm-template-whatif#58]
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.EventHub/namespaces
Microsoft.EventHub/namespaces/eventHubs
Microsoft.EventHub/namespaces/eventHubs/authorizationRules
Microsoft.EventHub/namespaces/eventHubs/authorizationRules/consumerGroups
Probably Microsoft.EventHub/namespaces/authorizationRules is also affected by these as the properties of those are similar to Microsoft.EventHub/namespaces/eventHubs/authorizationRules

Microsoft.EventHub/namespaces/disasterRecoveryConfigs

**apiVersion** (i.e. 2019-04-01)
In code

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
No changes to the resources

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

```
Resource and property changes are indicated with these symbols:
  - Delete
  + Create
  ~ Modify
  = NoChange

The deployment will update the following scopes:

Scope: /subscriptions/<subscription id>

  = resourceGroups/<resource group name> [2020-01-01]

Scope: /subscriptions/<subscription id>/resourceGroups/<resource group name>

  ~ Microsoft.EventHub/namespaces/lzaztesthub02 [2017-04-01]
    - properties.kafkaEnabled: true
    - properties.status:       "Active"

  ~ Microsoft.EventHub/namespaces/lzaztesthub02/eventHubs/hub001 [2017-04-01]
    - location: "West Europe"

  ~ Microsoft.EventHub/namespaces/lzaztesthub02/eventHubs/hub001/authorizationRules/testpolicy-1 [2017-04-01]
    - location: "West Europe"
    ~ properties.rights: [
      - 0: "Manage"
      + 0: "manage"
      - 1: "Send"
      + 1: "send"
      - 2: "Listen"
      + 2: "listen"
      ]

  ~ Microsoft.EventHub/namespaces/lzaztesthub02/eventHubs/hub001/authorizationRules/testpolicy-2 [2017-04-01]
    - location: "West Europe"
    ~ properties.rights: [
      - 0: "Send"
      + 0: "send"
      ]

  ~ Microsoft.EventHub/namespaces/lzaztesthub02/eventHubs/hub001/consumerGroups/group001 [2017-04-01]
    - location: "West Europe"

  ~ Microsoft.EventHub/namespaces/lzaztesthub02/eventHubs/hub001/consumerGroups/group002 [2017-04-01]
    - location: "West Europe"

  = Microsoft.EventHub/namespaces/lzaztesthub02/networkRuleSets/default [2018-01-01-preview]

```

On the latest versions of namespaces there is even more noise:

```

  ~ Microsoft.EventHub/namespaces/lzaztesthub02 [2018-01-01-preview]
    - properties.kafkaEnabled:  true
    - properties.status:        "Active"
    - properties.zoneRedundant: false
```
if you specify the properties (without status) on the namespace they will not be reported as change.

This one is problem too

```
  ~ Microsoft.EventHub/namespaces/lzaztesthub02/disasterRecoveryConfigs/repl0001 [2017-04-01]
    - properties.type: "MetadataReplication"
```
I am not specifying that property and I doubt that property can be changed. Also it is not documented.

**Additional context**

**Comment by shenglol** [comment]
[w22].

**Comment by alex-frankel** [comment]
This fix should be fully deployed. Please let us know if you still see this issue.
