### ISSUE TITLE
Microsoft.Network/publicIPAddresses

### ISSUE THREAD

**Issue by slavizh** [Azure/arm-template-whatif#59]
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.Network/publicIPAddresses

**apiVersion** (i.e. 2019-04-01)
2020-04-01

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
No change. Read only property natGateway should not change as association happens on Nat Gateway resource so this property is only read only.

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

```
  ~ Microsoft.Network/publicIPAddresses/pubip0004 [2020-04-01]
    - properties.natGateway:

        id: "/subscriptions/<subscriptionId>/resourceGroups/test-vnet-rg-1/providers/Microsoft.Network/natGateways/natgw00002"

```

**Additional context**

**Comment by shenglol** [comment]
[w24].

**Comment by alex-frankel** [comment]
This fix should be deployed. Let us know if you continue to see noise.
