### ISSUE TITLE
Microsoft.Network/privateEndpoints

### ISSUE THREAD

**Issue by slavizh** [Azure/arm-template-whatif#61]
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.Network/privateEndpoints

**apiVersion** (i.e. 2019-04-01)
2019-11-01
2020-04-01

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
No change in privateLinkServiceConnections property

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

```
 ~ Microsoft.Network/privateEndpoints/production-keyVault [2019-11-01]
    ~ properties.privateLinkServiceConnections: [
      ~ 0:

        - id: "/subscriptions/<subscription id>/resourceGroups/test-vnet-rg-1/providers/Microsoft.Network/privateEndpoints/production-keyVault/privateLinkServiceConnections/serviceConnection-production-keyVault"

      ]

```

```
  ~ Microsoft.Network/privateEndpoints/production-keyVault [2020-04-01]
    - properties.customDnsConfigs: [
        0:

          fqdn: "lz-kv-prd.vault.azure.net"
          ipAddresses: [
            0: "10.0.3.4"
          ]

      ]
    ~ properties.privateLinkServiceConnections: [
      ~ 0:

        - id: "/subscriptions/<subscription id>/resourceGroups/test-vnet-rg-1/providers/Microsoft.Network/privateEndpoints/production-keyVault/privateLinkServiceConnections/serviceConnection-production-keyVault"

      ]

```

**Additional context**

**Comment by shenglol** [comment]
[w25?]

**Comment by alex-frankel** [comment]
This fix should be fully deployed. Let us know if you are still seeing this noise.
