### ISSUE TITLE
Microsoft.Insights/components

### ISSUE THREAD

**Issue by mszadziul87** [Azure/arm-template-whatif#64]
## Describe the noise
Using What-If results in:
Error Code: InternalServerError
Error Message: Long running operation failed with status 'Failed'. Additional Info:'Encountered internal server error while processing the deployment what-if request. Diagnostic information: timestamp '20200520T111229Z', subscription id 'XXX', tracking id 'bc400ba5-5710-4611-be2f-c7034197c1cd', request correlation id '4507d817-0b07-4ded-b9c9-274fd82c6086'.'
Error Details: []
Request Id: 53b9782a-9ee0-4bc0-814c-43fb7ddb1a7a
Timestamp (UTC): 05/20/2020 11:12:43
**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.Insights/components
**apiVersion** (i.e. 2019-04-01)
2020-02-02-preview
2018-05-01-preview
2015-05-01
2014-04-01
**Client (PowerShell, Azure CLI, or API)**
PowerShell
**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**
```JSONC
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "AllParams": {
      "type": "object"
    }
  },
  "variables": {
    "Delimiters": [ ",", ";" ],
    "EnvironmentNames": "[split(parameters('AllParams').WebPart.Environments, variables('Delimiters'))]"
  },
  "resources": [
    // Application Insights
    {
      "apiVersion": "2015-05-01",
      "name": "[concat(parameters('AllParams').WebPart.AppInsightsName,'-',variables('EnvironmentNames')[copyIndex()])]",
      "type": "Microsoft.Insights/components",
      "location": "[resourceGroup().location]",
      "tags": "[resourceGroup().tags]",
      "properties": {
      },
      "copy": {
        "name": "AppInsightsCopy",
        "count": "[length(variables('EnvironmentNames'))]"
      }
    }
  ],
  "outputs": {
  }
}

```
**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
Expected behaviour would be to show the results of Application Insights deployment operation.
The ARM template works fine without What-If
**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**
![image](https://user-images.githubusercontent.com/34235838/82440771-2c2e5b80-9a9d-11ea-9fb2-c24aa0cd1aa2.png)

**Additional context**

**Comment by shenglol** [comment]
Same root cause as the one in #66. [w21]

**Comment by alex-frankel** [comment]
This fix should be fully deployed. Please let us know if you still see this issue.
