### ISSUE TITLE
Microsoft.Web sites/config appsettings

### ISSUE THREAD

**Issue by mszadziul87** [Azure/arm-template-whatif#65]
## Describe the noise
Using What-If results in:
Error Code: MultipleErrorsOccurred
Error Message: Long running operation failed with status 'Failed'. Additional Info:'Multiple error occurred: DeploymentWhatIfResourceError,DeploymentWhatIfResourceError,DeploymentWhatIfResourceError,DeploymentWhatIfResourceError. Please see details.'
Error Details: [
  {
    "Code": "DeploymentWhatIfResourceError",
    "Message": "The request to predict template deployment changes to subscription 'XXX' and resource group 'XXX' has failed due to a resource error. See details for more information.",
    "Target": "/subscriptions/XXX/resourceGroups/XXX/providers/Microsoft.Web/sites/XXX/config/appsettings?api-version=2018-11-01",
    "Details": [
      {
        "Code": "DeploymentWhatIfResourceInvalidResponse",
        "Message": "The request '/subscriptions/XXX/resourceGroups/XXX/providers/Microsoft.Web/sites/XXX/config/appsettings?api-version=2018-11-01' resulted in an unexpected HTTP status code 'MethodNotAllowed'. Diagnostic information: timestamp '20200520T114726Z', tracking id 'ca1ad6e8-288c-4b4f-bb3c-4405d5f2ea78', request correlation id 'dcd64ae5-6b16-4941-9390-cc22bc266c31', location 'northeurope'.",
        "Target": "/subscriptions/XXX/resourceGroups/XXX/providers/Microsoft.Web/sites/XXX/config/appsettings?api-version=2018-11-01",
        "Details": [],
        "AdditionalInfo": []
      }
    ],
    "AdditionalInfo": []
  }
]
**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.Web sites/config
**apiVersion** (i.e. 2019-04-01)
2018-11-01
2015-08-01
**Client (PowerShell, Azure CLI, or API)**
PowerShell
**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**
```JSONC
// WebApp
{
    "type": "Microsoft.Web/sites",
    "apiVersion": "2016-08-01",
    "name": "[parameters('AllParams').WebPart.WebAppName]",
    "location": "[resourceGroup().location]",
    "tags": "[resourceGroup().tags]",
    "properties": {
        "name": "[parameters('AllParams').WebPart.WebAppName]",
        "serverFarmId": "[resourceId(parameters('AllParams').ResourceGroupPart.ServicePlanResourceGroup,'Microsoft.Web/serverfarms', parameters('AllParams').WebPart.ServicePlanName)]",
        "siteConfig": {
            "use32BitWorkerProcess": false,
            "AlwaysOn": true
        }
    },
    "resources": [
        // WebApp Sticky Slot Config
        {
            "type": "config",
            "apiVersion": "2018-11-01",
            "name": "slotconfignames",
            "dependsOn": [
                "[resourceId('Microsoft.Web/Sites', parameters('AllParams').WebPart.WebAppName)]"
            ],
            "properties": {
                "appSettingNames": [
                    "ASPNETCORE_ENVIRONMENT",
                    "APPINSIGHTS_INSTRUMENTATIONKEY"
                ]
            }
        },
        // WebApp General Config
        {
            "type": "config",
            "apiVersion": "2018-11-01",
            "name": "web",
            "dependsOn": [
                "[resourceId('Microsoft.Web/Sites', parameters('AllParams').WebPart.WebAppName)]"
            ],
            "properties": {
                "phpVersion": ""
            }
        },
        // WebApp AppSettings
        {
            "type": "config",
            "apiVersion": "2018-11-01",
            "name": "appsettings",
            "dependsOn": [
                "[resourceId('Microsoft.Web/sites', parameters('AllParams').WebPart.WebAppName)]"
            ],
            "properties": {
                "ASPNETCORE_ENVIRONMENT": "",
                "APPINSIGHTS_INSTRUMENTATIONKEY": "",
                "WEBSITE_HTTPLOGGING_RETENTION_DAYS": "3",
                "APPINSIGHTS_JAVASCRIPT_ENABLED": "true",
                "MSDEPLOY_RENAME_LOCKED_FILES": "1"
            }
        }
    ]
}


```
**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
Expected behaviour would be to show the results of App Settings deployment operation.
The ARM template works fine without What-If
**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**
See above.
**Additional context**

**Comment by alex-frankel** [comment]
This resourceType is violating the ARM RPC. We are working with them to get it resolved.

**Comment by vskbalineni** [comment]
Hi, I am facing similar problem when run what-if analysis on webapp. However its working fine for other Azure resources. Also find error details below for your reference. Let me know if the issue has resolved.

  MultipleErrorsOccurred - Long running operation failed with status 'Failed'. Additional Info:'Multiple error occurred: DeploymentWhatIfResourceError,DeploymentWhatIfResourceError,DeploymentWhatIfResourceError. Please
     | see details.' DeploymentWhatIfResourceError - The request to predict template deployment changes to scope '/subscriptions/xxxx-xxxxx-xxxxx-xxxxx/resourceGroups/xxxx-xxxx-xxxx' has failed due to a resource
     | error. See details for more information. DeploymentWhatIfResourceInvalidResponse - The request
     | '/subscriptions/xxxxx-xxxxxx-xxxxxxx/resourceGroups/xxxx-xxxx-xxxx/providers/Microsoft.Web/sites/xxxx-xxxx-xxxx-xx/config/appsettings?api-version=2015-08-01' resulted in an unexpected HTTP status code
     | 'MethodNotAllowed'. Diagnostic information: timestamp '20201210T163017Z', tracking id 'xxxx-xxxx-xxxx-xxxx', request correlation id 'abcdf-ffdfd-ddfd-fdffdfd', location 'canadacentral'.
     | DeploymentWhatIfResourceError - The request to predict template deployment changes to scope '/subscriptions/xxxxxx-xxxxx-xxxxx-xxxxx/resourceGroups/xxxx-xxxx-xxxx' has failed due to a resource error. See
     | details for more information. DeploymentWhatIfResourceInvalidResponse - The request
     | '/subscriptions/xxxxx-xxxxxx-xxxxxxx/resourceGroups/xxxx-xxxx-xxxx/providers/Microsoft.Web/sites/xxxx-xxxx-xxxx-xx/config/connectionstrings?api-version=2015-08-01' resulted in an unexpected HTTP status
     | code 'MethodNotAllowed'. Diagnostic information: timestamp '20201210T163017Z', tracking id 'xxxxx-xxxxx-xxxxx-xxxx', request correlation id 'jkdhgdkjf-745hbhf-hsds667', location 'canadacentral'.
     | DeploymentWhatIfResourceError - The request to predict template deployment changes to scope '/subscriptions/xxxxx-xxxxxx-xxxxxxx/resourceGroups/xxxx-xxxx-xxxx' has failed due to a resource error. See
     | details for more information. DeploymentWhatIfResourceInvalidResponse - The request
     | '/subscriptions/xxxxx-xxxxxx-xxxxxxx/resourceGroups/xxxx-xxxx-xxxx/providers/Microsoft.Web/sites/xxxx-xxxx-xxxx-xx/slots/Blue/config/appsettings?api-version=2015-08-01' resulted in an unexpected HTTP
     | status code 'MethodNotAllowed'. Diagnostic information: timestamp '20201210T163017Z', tracking id 'xxxx-xxxx-xxxx-xx', request correlation id 'xxxx-xxxxx-xxxxxx-xxxxx', location
     | 'canadacentral'.

**Comment by smolyakoff** [comment]
Hi, we are facing a similar issue. The "what if" commands doesn't work on the template with `appsettings` resources.

**Comment by konjp** [comment]
Also, to confirm that issue is not resolved, 8 months after... What is strange when I got this error 'location' in error message is different from 'location' that is specified in arm template.

**Comment by alex-frankel** [comment]
Apologies for the delay. We have opened an internal ticket to have the web site team make the necessary change to resolve this issue. Unfortunately, this is not a fix we can make on our side, we need the web sites team to make the fix. We should have an ETA in the first week of the new year.

I am also opening up an investigation to see if we can ignore these errors going forward assuming there may be other resources like this and #63 that have not implemented the GET method to get resource status. That is a good suggestion.

**Comment by jobinsj27** [comment]
Hi all, has an ETA been established yet. My team is also facing this issue.

**Comment by HRading** [comment]
We really need a fix for this issue, what is the ETA?
Have the issue with AppSettings referencing KeyVault secrets.

**Comment by miqm** [comment]
@alex-frankel any update on this?

**Comment by mohamed-shehata-m** [comment]
Is there any ETA to resolve this issue?

**Comment by alex-frankel** [comment]
@shenglol will resolving #73 also fix this one?

**Comment by shenglol** [comment]
Yes it should.

**Comment by alex-frankel** [comment]
Latest ETA is now mid-June.

**Comment by mickybar** [comment]
@alex-frankel any news about this issue?

**Comment by alex-frankel** [comment]
Latest ETA is 7/2.

**Comment by BrainScale-nitinm** [comment]
Any fixes for this?

**Comment by alex-frankel** [comment]
@seligj95 / @shenglol - do you happen to know if this issue has been resolved?

@mauve - that would have meant July 2nd, 2021

**Comment by shenglol** [comment]
It has been resolved. We have deployed a fix on the What-If side to show resources that don't support GET as `unsupported`. It looks like the web RP team has also fixed the ARM RPC violation.
