### ISSUE TITLE
Microsoft.Web/serverfarms

### ISSUE THREAD

**Issue by mszadziul87** [Azure/arm-template-whatif#66]
## Describe the noise
Using What-If results in:
Error Code: InternalServerError
Error Message: Long running operation failed with status 'Failed'. Additional Info:'Encountered internal server error while processing the deployment what-if request. Diagnostic information: timestamp '20200520T120424Z', subscription id 'XXX', tracking id '12f2f8af-1e56-4a0e-b622-df35fd566cb6', request correlation id '64956573-e707-4f5b-ab4c-91e37857b099'.'
Error Details: []
Request Id: 190120cf-6c07-48d5-b30f-46b10b5cfc8a
Timestamp (UTC): 05/20/2020 12:04:37
**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.Web/serverfarms
**apiVersion** (i.e. 2019-04-01)
2019-08-01
2015-08-01
**Client (PowerShell, Azure CLI, or API)**
PowerShell
**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**
```JSONC
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
      "AllParams": {
        "type": "object"
      }
    },
    "variables": {
    },
    "resources": [
      // App Service Plan
      {
        "type": "Microsoft.Web/serverfarms",
        "apiVersion": "2015-08-01",
        "name": "[parameters('AllParams').WebPart.ServicePlanName]",
        "location": "[resourceGroup().location]",
        "tags": "[resourceGroup().tags]",
        "sku": {
          "name": "[parameters('AllParams').WebPart.ServicePlanSkuName]",
          "capacity": "[parameters('AllParams').WebPart.ServicePlanSkuCapacity]"
        }
      }
    ],
    "outputs": {
    }
  }

```

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
Expected behaviour would be to show the results of App Service Plan deployment operation.
The ARM template works fine without What-If
**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**
![image](https://user-images.githubusercontent.com/34235838/82445365-f8efca80-9aa4-11ea-8f02-8d2e4aa1e972.png)

**Additional context**

**Comment by shenglol** [comment]
Hi @mszadziul87, thanks for reporting the issue. We already have a fix for this. You may expect it to be deployed within 2 weeks. [w21]

**Comment by alex-frankel** [comment]
This fix should be fully deployed. Please let us know if you still see this issue.
