### ISSUE TITLE
Microsoft.Authorization/policyDefinitions

### ISSUE THREAD

**Issue by slavizh** [Azure/arm-template-whatif#69]
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.Authorization/policyDefinitions

**apiVersion** (i.e. 2019-04-01)
2019-01-01

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
No changes to parameter types values

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

```
  ~ Microsoft.Authorization/policyDefinitions/add-vms-to-backup [2019-01-01]

    ~ properties.parameters.imageOffers.type:        "Array" => "array"
    ~ properties.parameters.imagePublishers.type:    "Array" => "array"
    ~ properties.parameters.imageSkus.type:          "Array" => "array"
    ~ properties.parameters.policyName.type:         "String" => "string"
    ~ properties.parameters.vaultLocation.type:      "String" => "string"
    ~ properties.parameters.vaultName.type:          "String" => "string"
    ~ properties.parameters.vaultResourceGroup.type: "String" => "string"

```

**Additional context**

**Comment by majastrz** [comment]
Yeah, we need to mark these as case-insensitive.

**Comment by alex-frankel** [comment]
Need to understand why these are not marked as enum values in swagger and why this wasn't automatically detected

**Comment by shenglol** [comment]
[w26]

**Comment by alex-frankel** [comment]
This should be resolved, let us know if you still see this noise
