### ISSUE TITLE
New-AzDeploymentWhatIf should be New-AzDeployment -WhatIf

### ISSUE THREAD

**Issue by KevinMarquette** [Azure/arm-template-whatif#7]
**Describe the bug**
This cmdlet is inappropriately named. I thought it was a bug in the documentation. The expected Powershell syntax is:

    New-AzDeployment -WhatIf

WhatIf support is built into Powershell as a language feature. Implementing this correctly will make it easier to understand and use in other scripts. 

This command is either named wrong or should be implemented as New-AzDeployment -WhatIf

**Comment by KevinMarquette** [comment]
Looks like this was already reported here: https://github.com/Azure/azure-powershell/issues/10619

**Comment by alex-frankel** [comment]
This may be something we implement. During our initial conversations, we were advised not to use that -WhatIf flag because -WhatIf is a client side operation, not server side. This feedback should help our case, so keep it coming :)

**Comment by alex-frankel** [comment]
This is done - we haven't yet updated the docs, but the latest release supports both `-WhatIf` and 
`-Confirm` behavior. Confirm in particular works really nice because I can do WhatIf and then say `Y` to kick of the deployment
