### ISSUE TITLE
Microsoft.StreamAnalytics/streamingJobs

### ISSUE THREAD

**Issue by slavizh** [Azure/arm-template-whatif#71]
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.StreamAnalytics/streamingJobs

**apiVersion** (i.e. 2019-04-01)
2017-04-01-preview

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
Properties should not change

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

```
Scope: /subscriptions/<subscription id>/resourceGroups/lz-stream-analytics-rg

  ~ Microsoft.StreamAnalytics/streamingJobs/lzaztestsaj01 [2017-04-01-preview]
    - properties.contentStoragePolicy: "SystemAccount"
    - properties.jobType:              "Cloud"
    + properties.transformation:

        name:                   "lzaztestsaj01Query"
        properties.query:       "SELECT
  *
INTO
   [YourOutputAlias]
FROM
   [YourInputAlias]"
        properties.streamUnits: 1

```

**Additional context**

**Comment by shenglol** [comment]
[w45].

**Comment by alex-frankel** [comment]
This fix should be fully deployed. Let us know if you are still setting this issue.
