### ISSUE TITLE
WhatIf doesn't support deployment references

### ISSUE THREAD

**Issue by alexwilsh** [Azure/arm-template-whatif#72]
**Describe the bug**
Our template contains deployment references to ARM templates stored in Blob Storage.
Parameter file provides the URL to blob storage and SAS token for access to it.
In this combination, WhatIf returns 'no change' like there is no resources defined at all.

**To Reproduce**
1. Create ARM template with resources of the 'Microsoft.Resources/deployments' type
2. ARM template should have two parameters: URI to Blob Storage and SAS token for it.
3. Each resource should have templateLink defined with URI that basically combines Blob Storage URI, path to an ARM template within the blob container and SAS token
3. Run New-AzDeployment command with -WhatIf switch or Get-AzDeploymentWhatIfResult
4. Observe the result similar to 'Resource changes: no change.'

**Expected behavior**
Support referenced templates same way as real deployment does 

**Client**
PowerShell Core, Mac.

**Comment by alex-frankel** [comment]
Can you share the "mainTemplate" and the template that is being referenced? I just did a quick test of this with a deployment that references a template stored at a raw github url and it worked as expected. As long as the URL resolves at the time what-if was called, everything should work.

**Comment by alexwilsh** [comment]
Well, it didn't work for me last time when I tried on our real examples.
Today I tried to reproduce the same using much simpler templates to provide you with the example, but it worked this time.
I guess there is something in our set up that doesn't allow What-If feature work properly. Maybe unsupported resources or anything like that.

Let me then try to figure that out on a complex case and I'll come back to you if I find something interesting.
Closing this issue for now.

Thanks for the help!

**Comment by alexwilsh** [comment]
Alright, it took me a while to figure this out, but I guess I found in which cases WhatIf doesn't work properly.
The problem is related to the 'reference' function.

What we have:
- Blob storage with the structure similar to this:
![image](https://user-images.githubusercontent.com/22404115/84431850-d99a1800-abe0-11ea-882c-3351b951809d.png)
- basically, 2 linked templates (building-blocks) and 2 master templates that mix and match building blocks to create a logic:
   - ai-linked has AppInsights resource defined
   - rg-linked has Resource Group resource defined
   - ai-master just references ai-linked as a nested template
   - rg-master references rg-linked templates to create bunch of Resource Groups. This template has the output object with the name of a main Resource Group as a property in it (for testing purposes)
- then we have main ARM template like this:
```{
  "$schema": "https://schema.management.azure.com/schemas/2018-05-01/subscriptionDeploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "baseTemplateUri": {
      "type": "string",
      "metadata": {
        "description": "Uri to a Blob Storage container where all ARM templates are stored"
      }
    },
    "sasToken": {
      "type": "securestring",
      "metadata": {
        "description": "A SAS token for access to Storage Account with all available ARM templates published"
      }
    },
    "location": {
      "type": "string",
      "metadata": {
        "description": "Location for the deployment resources"
      }
    }
  },
  "variables": {
    "rgtemplateName": "[concat(parameters('baseTemplateUri'), 'test/master/rg-master.json', parameters('sasToken'))]",
    "aitemplateName": "[concat(parameters('baseTemplateUri'), 'test/master/ai-master.json', parameters('sasToken'))]"
  },
  "resources": [
    {
      "name": "[concat(deployment().name, '-rgs')]",
      "type": "Microsoft.Resources/deployments",
      "apiVersion": "2019-10-01",
      "location": "[parameters('location')]",
      "properties": {
        "mode": "Incremental",
        "templateLink": {
          "uri": "[variables('rgtemplateName')]",
          "contentVersion": "1.0.0.0"
        },
        "parameters": {
          "baseTemplateUri": {
            "value": "[parameters('baseTemplateUri')]"
          },
          "sasToken": {
            "value": "[parameters('sasToken')]"
          },
          "location": {
            "value": "[parameters('location')]"
          }
        }
      }
    },
    {
      "name": "[concat(deployment().name, '-ais')]",
      "type": "Microsoft.Resources/deployments",
      "apiVersion": "2019-10-01",
      "location": "[parameters('location')]",
      "properties": {
        "mode": "Incremental",
        "templateLink": {
          "uri": "[variables('aitemplateName')]",
          "contentVersion": "1.0.0.0"
        },
        "parameters": {
          "baseTemplateUri": {
            "value": "[parameters('baseTemplateUri')]"
          },
          "sasToken": {
            "value": "[parameters('sasToken')]"
          },
          "location": {
            "value": "[parameters('location')]"
          },
          "rgname": {
            "value": "[reference(concat(deployment().name, '-rgs')).outputs.resource.name]"
          }
        }
      }
    }
  ],
  "outputs": {
  }
}
```
- obviously the parameter file for this template will have URI to a Blob Storage, SAS token, and location

Please notice that the main template references the rg-master template to deploy all required ResourceGroups and the ai-master template to deploy AppInsights-related resources. The definition of ai-master nested template passes the value from RG master resource as a value for the rgname parameter by using the 'reference' function.
The main issue is exactly related to this fact.

If I remove that reference function and just pass raw name as a value for the rgname parameter, WhatIf will show me relevant information:
![image](https://user-images.githubusercontent.com/22404115/84433111-a8bae280-abe2-11ea-9b3f-ca947361163e.png)

But with the reference function is in place, WhatIf just skips the resource completely:
![image](https://user-images.githubusercontent.com/22404115/84433267-e0298f00-abe2-11ea-88ab-95e212c6cc35.png)

In our case, we have much more complicated schema, but we use the 'reference' function a lot and all our deployment resources depend on each other - that is why I saw just 'No changes' when I ran WhatIf for our real templates.

What is even more interesting, since WhatIf in this case doesn't see any resources, it doesn't go inside and obviously doesn't validate ARM templates referenced in there. Which is kinda clear now why, but was confusing in the beginning. 
I just thought that the preview version had issues :)

**Comment by alex-frankel** [comment]
OK thanks for the update - we think you are right that it is because of the reference() function for the rgName. We are doing a bit more investigation on our end to confirm this.

**Comment by alex-frankel** [comment]
Closing as it is a dup of #83
