### ISSUE TITLE
Microsoft.ApiManagement/service/apis

### ISSUE THREAD

**Issue by JanneMattila** [Azure/arm-template-whatif#75]
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.ApiManagement/service/apis

**apiVersion** (i.e. 2019-04-01)
2019-01-01

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**
[link to relevant clip](https://github.com/JanneMattila/329-azure-api-management/blob/e78bb1025d4ba987acbe1f58f16e4ac246d8b00b/deploy/api/httpbin/api.json#L26-L40)

```json
    {
      "name": "[variables('apiResourceName')]",
      "type": "Microsoft.ApiManagement/service/apis",
      "apiVersion": "2019-01-01",
      "properties": {
        "displayName": "HTTP Bin API",
        "description": "API Management facade for a very handy and free online HTTP tool",
        "serviceUrl": "[parameters('serviceUrl')]",
        "path": "[variables('apiPath')]",
        "subscriptionRequired": false,
        "protocols": [
          "https"
        ]
      }
    },
```

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
Expected no noise

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

```cmd
  ~ Microsoft.ApiManagement/service/{serviceName}/apis/{apiName} [2019-01-01]
    - properties.apiRevision: "1"
    - properties.subscriptionKeyParameterNames:

        header: "Ocp-Apim-Subscription-Key"
        query:  "subscription-key"
```

**Additional context**
-

**Comment by detienne20** [comment]
We believe we resolved all of the noise reported as part of this issue (https://github.com/Azure/arm-template-whatif/issues/77). Fix should have been fully deployed in w44. Please let us know if you are still seeing this issue.
