### ISSUE TITLE
Microsoft.Web/sites

### ISSUE THREAD

**Issue by slavizh** [Azure/arm-template-whatif#80]
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.Web/sites

**apiVersion** (i.e. 2019-04-01)
2019-08-01

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
No changes. Could be more properties that act like this.

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

```
  ~ Microsoft.Web/sites/app3434ssfdfsdf [2019-08-01]
    - kind:                                        "app"
    + identity:

        type: "None"

    + properties.siteConfig.alwaysOn:              false
    + properties.siteConfig.cors:

        supportCredentials: false

    + properties.siteConfig.http20Enabled:         true
    + properties.siteConfig.localMySqlEnabled:     false
    + properties.siteConfig.minTlsVersion:         "1.2"
    + properties.siteConfig.netFrameworkVersion:   "v4.6"
    + properties.siteConfig.use32BitWorkerProcess: true
    + properties.siteConfig.webSocketsEnabled:     false

```

**Additional context**

**Comment by shenglol** [comment]
Dup of #https://github.com/Azure/arm-template-whatif/issues/90.

**Comment by alex-frankel** [comment]
closing since this is a duplicate
