### ISSUE TITLE
Microsoft.Web/sites/config/logs

### ISSUE THREAD

**Issue by slavizh** [Azure/arm-template-whatif#81]
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.Web/sites/config
**apiVersion** (i.e. 2019-04-01)
2019-08-01

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
No change

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

```
~ Microsoft.Web/sites/app3434ssfdfsdf/config/logs [2019-08-01]
    + properties.httpLogs.fileSystem.retentionInDays: 7
```

**Additional context**

**Comment by shenglol** [comment]
@slavizh I could not reproduce this. Do you mind checking if the noise still shows up? I wonder if the web PR did something already to fix it.

**Comment by slavizh** [comment]
@shenglol I will check if I can test next week. This week was too busy and I couldn't reach to this item.

**Comment by slavizh** [comment]
@shenglol seems that particular issue does not appear in what-if as noise anymore. This can be closed.

**Comment by shenglol** [comment]
@slavizh thanks for confirming!
