### ISSUE TITLE
App Service Envrionment (Microsoft.web/hostingEnviornment) noise

### ISSUE THREAD

**Issue by edwinsummers** [Azure/arm-template-whatif#84]
## Describe the noise

**Resource type**  Microsoft.Web/hostingEnvironments

**apiVersion** 2015-08-01

**Client (PowerShell, Azure CLI, or API)**  PowerShell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**

      {
        "apiVersion": "2015-08-01",
        "type": "Microsoft.Web/hostingEnvironments",
        "name": "[parameters('aseName')]",
        "kind": "ASEV2",
        "location": "[parameters('aseLocation')]",
        "properties": {
          "name": "[parameters('aseName')]",
          "location": "[parameters('aseLocation')]",
          "ipSslAddressCount": 0,
          "internalLoadBalancingMode": "[parameters('internalLoadBalancingMode')]",
          "virtualNetwork": {
            "Id": "[variables('vnetID')]",
            "Subnet": "[parameters('subnetName')]"
          }
        }
      }

**Expected response**   I expected no noise since the template has not been modified since the resources were deployed  (WhatIf run on same template immediately after deployment)

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

      ~ Microsoft.Web/hostingEnvironments/armASE [2015-08-01]
        - properties.allowedMultiSizes:          "Medium,Large,ExtraLarge,Standard_D2,Standard_D3,Standard_D4,Standard_D1_V2,Standard_D2_V2,Standard_D3_V2,Standard_D4_V2"
        - properties.allowedWorkerSizes:         "Small,Medium,Large,ExtraLarge,Standard_D1,Standard_D2,Standard_D3,Standard_D4,Standard_D1_V2,Standard_D2_V2,Standard_D3_V2,Standard_D4_V2"
        - properties.databaseEdition:            "Standard"
        - properties.databaseServiceObjective:   "S1"
        - properties.defaultFrontEndScaleFactor: 15
        - properties.dnsSuffix:                  "armASE.appserviceenvironment.us"
        - properties.environmentIsHealthy:       true
        - properties.environmentStatus:          "True||"
        - properties.frontEndScaleFactor:        15
        - properties.hasLinuxWorkers:            false
        - properties.lastAction:                 "PrevalidateAndStompDeploy"
        - properties.lastActionResult:           "Done"
        - properties.maximumNumberOfMachines:    250
        - properties.multiRoleCount:             2
        - properties.multiSize:                  "Standard_D1_V2"
        - properties.publicHost:                 "<redacted>.usgovcloudapp.net"
        - properties.resourceGroup:              "rg-armAseDeploy"
        - properties.subscriptionId:             "<redacted>"
        - properties.upgradeDomains:             20
        - properties.upgradePreference:          "None"
        - properties.virtualNetwork.name:        "<redacted>"
        - properties.virtualNetwork.type:        "Microsoft.Network/virtualNetworks"
        - properties.vnetName:                   "<redacted>"
        - properties.vnetResourceGroupName:      "<redacted>"
        - properties.vnetSubnetName:             "ase2"
    
    
    Resource changes: 1 to modify.

**Additional context**

1.  Note this resource in the USGov Virginia region
2. The WhatIf output also showed Tags being deleted. No Tags were included in the ARM template, but we have an Azure Policy in this Subscription that adds standard tags to all resources. I removed the Tags changes from the WhatIf output above since I considered this to be a legitimate finding.

**Comment by shenglol** [comment]
[w47].

**Comment by alex-frankel** [comment]
This noise issue should be resolved and fully deployed. Please let us know if you are still able to reproduce the issue.
