### ISSUE TITLE
Microsoft.DataLakeStore/accounts

### ISSUE THREAD

**Issue by slavizh** [Azure/arm-template-whatif#85]
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.DataLakeStore/accounts

**apiVersion** (i.e. 2019-04-01)
2016-11-01

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**

No changes. The properties are not specified in the template.

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

```
  ~ Microsoft.DataLakeStore/accounts/adlsv1lztest [2016-11-01]
    - properties.dataLakePerformanceTierState:   "Disabled"
    - properties.firewallAllowDataLakeAnalytics: "Disabled"
    - properties.trustedIdProviderState:         "Disabled"
```

**Additional context**

**Comment by alex-frankel** [comment]
[w40]

**Comment by alex-frankel** [comment]
This fix should be deployed. Let us know if you are still seeing this issue.
