### ISSUE TITLE
Microsoft.Network/dnsZones

### ISSUE THREAD

**Issue by slavizh** [Azure/arm-template-whatif#87]
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.Network/dnsZones

**apiVersion** (i.e. 2019-04-01)
2018-05-01

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
No changes.
Also any of the different type records if they are not in the template what-if does not lists those as ignored.

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

```
~ Microsoft.Network/dnsZones/lz001.net/A/stan3 [2018-05-01]
    + location: "Global"

  ~ Microsoft.Network/dnsZones/lz001.net/AAAA/stan2 [2018-05-01]
    + location: "Global"
[
      ~ 0:

        ~ ipv6Address: "2001:db8:85a3::8a2e:370:7334" => "2001:0db8:85a3:0000:0000:8a2e:0370:7334"

      ~ 1:

        ~ ipv6Address: "2001:db8:85a3::8a2e:370:7335" => "2001:0db8:85a3:0000:0000:8a2e:0370:7335"

      ]

~ Microsoft.Network/dnsZones/lz001.net/CNAME/stan5 [2018-05-01]
    + location: "Global"

  ~ Microsoft.Network/dnsZones/lz001.net/MX/stan6 [2018-05-01]
    + location: "Global"

  ~ Microsoft.Network/dnsZones/lz001.net/NS/stan7 [2018-05-01]
    + location: "Global"

  ~ Microsoft.Network/dnsZones/lz001.net/PTR/stan10 [2018-05-01]
    + location: "Global"

  ~ Microsoft.Network/dnsZones/lz001.net/SRV/stan8 [2018-05-01]
    + location: "Global"

  ~ Microsoft.Network/dnsZones/lz001.net/TXT/stan9 [2018-05-01]
    + location: "Global"

  = Microsoft.Network/dnsZones/lz001.net [2018-05-01]
  = Microsoft.Network/dnsZones/lz002.net [2018-05-01]

```

There are changes in location which is specified in the template resources. Also for Microsoft.Network/dnsZones/lz001.net/AAAA/stan2  I am putting values 2001:0db8:85a3:0000:0000:8a2e:0370:7334 and 2001:0db8:85a3:0000:0000:8a2e:0370:7335 but seems later changed by the service which results like a change in every deployment.

**Additional context**

**Comment by alex-frankel** [comment]
* We are taking an action to normalize the ipv6 addresses to eliminate that noise
* we are investigating the `"location": "global"` noise
* separately, we need a larger enhancement to support identifying these dnsRecord resources when they are not declared in the template

**Comment by shenglol** [comment]
IPv6 normalization was done and is waiting on deployment [w28].

**Comment by shenglol** [comment]
The `location` properties are defined on the Microsoft.Network/dnsZones resource type, but they are not supported by those DNS record set child resource types. The quick fix would be removing them from the ARM template.

**Comment by alex-frankel** [comment]
The IPv6 normalization should be fully deployed. We are going to close this issue as you can resolve the use of the `location` property yourself.
