### ISSUE TITLE
Microsoft.SignalRService/signalR

### ISSUE THREAD

**Issue by slavizh** [Azure/arm-template-whatif#93]
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
Microsoft.SignalRService/signalR

**apiVersion** (i.e. 2019-04-01)
2018-10-01]

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
No changes to resource

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

```
 ~ Microsoft.SignalRService/signalR/sentiatest01 [2018-10-01]
    - properties.hostNamePrefix: "sentiatest01"
    - sku.size:                  "F1"
[
      - 2:

          flag:  "EnableMessagingLogs"
          value: "False"

      ]


```

**Additional context**

**Comment by shenglol** [comment]
[w31]

**Comment by alex-frankel** [comment]
This should be resolved, let us know if you still see this noise
