### ISSUE TITLE
 Microsoft.Network/loadBalancers

### ISSUE THREAD

**Issue by slavizh** [Azure/arm-template-whatif#99]
## Describe the noise

**Resource type** (i.e. Microsoft.Storage/storageAccounts)
 Microsoft.Network/loadBalancers

**apiVersion** (i.e. 2019-04-01)
2020-04-01

**Client (PowerShell, Azure CLI, or API)**
PowerShell

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**
Private IP Address is either provided property or it is automatically filled by the service (static vs Dynamic). When it is dynamic it should not be marked as change during deployment. When it is dynamic you set the privateIPAddress to value null.

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

```
~ Microsoft.Network/loadBalancers/azlbn002 [2020-04-01]
[
      ~ 0:

        - properties.privateIPAddress: "10.2.1.4"

      ]

```

**Additional context**

**Comment by shenglol** [comment]
Just realized that there's a bug (not related to the noise) - the output formatter failed to print the property path for array changes, which is a regression. I'll fix it in our upcoming PS release.

**Comment by alex-frankel** [comment]
The powershell bug fix will be released by 8/26. We still need to resolve the noise issue.

**Comment by shenglol** [comment]
The noise reduction work was done [w32].

**Comment by alex-frankel** [comment]
Fix should be fully deployed
